In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path = "Downloads/hospital_analytics_dataset"

In [3]:
patients = pd.read_csv(f"{path}/patients.csv")
doctors = pd.read_csv(f"{path}/doctors.csv")
departments = pd.read_csv(f"{path}/departments.csv")
appointments = pd.read_csv(f"{path}/appointments.csv")
admissions = pd.read_csv(f"{path}/admissions.csv")
treatments = pd.read_csv(f"{path}/treatments.csv")

In [4]:
datasets={
    "Patients":patients,
    "Doctors":doctors,
    "Departments":departments,
    "Appointments":appointments,
    "Admissions":admissions,
    "Treatment":treatments 
}
for name,df in datasets.items():
     print(f"{name},{df.shape}")

Patients,(12015, 8)
Doctors,(80, 6)
Departments,(8, 6)
Appointments,(45000, 9)
Admissions,(9000, 10)
Treatment,(18000, 8)

In [5]:
patients.head(5)

,patient_id,patient_name,gender,date_of_birth,city,state,registration_date,insurance_type
0,100001,Patient_100001,Male,1966-05-04,Trichy,Tamil Nadu,2024-09-09,Corporate
1,100002,Patient_100002,Male,2018-09-25,Mumbai,Maharashtra,2025-05-22,Private
2,100003,Patient_100003,Male,2000-08-20,Visakhapatnam,Andhra Pradesh,2024-01-06,Private
3,100004,Patient_100004,Female,2000-10-31,Kochi,Kerala,2025-03-12,Private
4,100005,Patient_100005,Female,1955-06-23,Hyderabad,Telangana,2025-04-12,Government

In [6]:
doctors.head(5)

,doctor_id,doctor_name,department_id,specialization,experience_years,employment_type
0,2001,Dr_2001,102,Cardiology,8.0,Full-Time
1,2002,Dr_2002,107,Dermatology,1.0,Part-Time
2,2003,Dr_2003,103,Orthopedics,8.0,Full-Time
3,2004,Dr_2004,101,Emergency Medicine,NaN,Full-Time
4,2005,Dr_2005,106,General Medicine,21.0,Full-Time

In [7]:
departments.head()

,department_id,department_name,department_type,total_beds,available_beds,staff_count
0,101,Emergency,Emergency,40,12,42
1,102,Cardiology,Specialty,35,10,38
2,103,Orthopedics,Specialty,30,9,32
3,104,Neurology,Specialty,25,7,29
4,105,Pediatrics,Specialty,30,11,35

In [8]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_type,appointment_status,waiting_time_minutes,satisfaction_score
0,300001,106888,2002,2025-02-06,08:00,Emergency,Completed,15.0,5.0
1,300002,101312,2010,2026-04-12,08:00,Consultation,No-Show,0.0,NaN
2,300003,104026,2061,2025-04-16,18:45,Consultation,Cancelled,0.0,NaN
3,300004,105386,2010,2026-04-04,14:00,Diagnostic,Completed,52.0,3.0
4,300005,102881,2062,2025-04-13,08:30,Diagnostic,Rescheduled,68.0,NaN

In [9]:
admissions.head()

,admission_id,patient_id,doctor_id,department_id,admission_date,discharge_date,admission_type,bed_number,admission_status,readmission_flag
0,400001,106741,2029,102,2025-02-15,2025-02-19,Elective,102-03,Discharged,False
1,400002,106693,2005,106,2025-06-01,2025-06-05,Elective,106-27,Discharged,False
2,400003,102502,2033,105,2026-02-06,2026-02-09,Elective,105-41,Discharged,False
3,400004,103112,2047,102,2025-02-23,2025-02-26,Elective,102-01,Discharged,False
4,400005,110514,2022,101,2026-06-16,2026-06-20,Referral,101-24,Discharged,False

In [10]:
treatments.head()

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved
1,500002,404182,2026-03-14,Pregnancy-related,Surgery,3860.45,78,Improved
2,500003,407778,2025-02-01,Asthma,Diagnostic Test,500.19,68,Improved
3,500004,404983,2025-11-07,Pregnancy-related,Consultation,3070.55,94,Referred
4,500005,400587,2025-11-23,Migraine,Surgery,1265.82,51,Improved

In [11]:
for name,df in datasets.items():
     print("\n",name) 
     print(df.dtypes)

 Patients
patient_id           int64
patient_name           str
gender                 str
date_of_birth          str
city                   str
state                  str
registration_date      str
insurance_type         str
dtype: object

 Doctors
doctor_id             int64
doctor_name             str
department_id         int64
specialization          str
experience_years    float64
employment_type         str
dtype: object

 Departments
department_id      int64
department_name      str
department_type      str
total_beds         int64
available_beds     int64
staff_count        int64
dtype: object

 Appointments
appointment_id            int64
patient_id                int64
doctor_id                 int64
appointment_date            str
appointment_time            str
appointment_type            str
appointment_status          str
waiting_time_minutes    float64
satisfaction_score      float64
dtype: object

 Admissions
admission_id        int64
patient_id          int64
doctor_id           int64
department_id       int64
admission_date        str
discharge_date        str
admission_type        str
bed_number            str
admission_status      str
readmission_flag     bool
dtype: object

 Treatment
treatment_id                    int64
admission_id                    int64
treatment_date                    str
diagnosis                         str
treatment_type                    str
treatment_cost                float64
treatment_duration_minutes      int64
treatment_outcome                 str
dtype: object

In [12]:
for name,df in datasets.items():
     print("\n",name) 
     print(df.columns.tolist())

 Patients
['patient_id', 'patient_name', 'gender', 'date_of_birth', 'city', 'state', 'registration_date', 'insurance_type']

 Doctors
['doctor_id', 'doctor_name', 'department_id', 'specialization', 'experience_years', 'employment_type']

 Departments
['department_id', 'department_name', 'department_type', 'total_beds', 'available_beds', 'staff_count']

 Appointments
['appointment_id', 'patient_id', 'doctor_id', 'appointment_date', 'appointment_time', 'appointment_type', 'appointment_status', 'waiting_time_minutes', 'satisfaction_score']

 Admissions
['admission_id', 'patient_id', 'doctor_id', 'department_id', 'admission_date', 'discharge_date', 'admission_type', 'bed_number', 'admission_status', 'readmission_flag']

 Treatment
['treatment_id', 'admission_id', 'treatment_date', 'diagnosis', 'treatment_type', 'treatment_cost', 'treatment_duration_minutes', 'treatment_outcome']

In [13]:
for name,df in datasets.items():
     print("\n",name) 
     print(df.isnull().sum())

 Patients
patient_id            0
patient_name          0
gender                0
date_of_birth         0
city                 60
state                 0
registration_date     0
insurance_type       35
dtype: int64

 Doctors
doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    5
employment_type     0
dtype: int64

 Departments
department_id      0
department_name    0
department_type    0
total_beds         0
available_beds     0
staff_count        0
dtype: int64

 Appointments
appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes     120
satisfaction_score      9929
dtype: int64

 Admissions
admission_id        0
patient_id          0
doctor_id           0
department_id       0
admission_date      0
discharge_date      0
admission_type      0
bed_number          0
admission_status    0
readmission_flag    0
dtype: int64

 Treatment
treatment_id                   0
admission_id                   0
treatment_date                 0
diagnosis                      0
treatment_type                 0
treatment_cost                80
treatment_duration_minutes     0
treatment_outcome              0
dtype: int64

In [14]:
for name,df in datasets.items():
     print(name,"duplicates:",df.duplicated().sum())

Patients duplicates: 15
Doctors duplicates: 0
Departments duplicates: 0
Appointments duplicates: 0
Admissions duplicates: 0
Treatment duplicates: 0

In [15]:
print(patients["gender"].unique())
print(patients["insurance_type"].unique())

print(appointments["appointment_status"].unique())
print(appointments["appointment_type"].unique())

print(admissions["admission_type"].unique())

print(treatments["treatment_type"].unique())

<StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
<StringArray>
['Corporate', 'Private', 'Government', 'Self-Pay', nan]
Length: 5, dtype: str
<StringArray>
['Completed', 'No-Show', 'Cancelled', 'Rescheduled']
Length: 4, dtype: str
<StringArray>
['Emergency', 'Consultation', 'Diagnostic', 'Follow-Up']
Length: 4, dtype: str
<StringArray>
['Elective', 'Referral', 'Emergency']
Length: 3, dtype: str
<StringArray>
['Diagnostic Test',         'Surgery',    'Consultation',      'Medication',
       'Procedure',         'Therapy']
Length: 6, dtype: str

In [16]:
patients.describe()

          patient_id
count   12015.000000
mean   106001.074490
std      3464.255314
min    100001.000000
25%    103000.500000
50%    106002.000000
75%    108999.500000
max    112000.000000

In [17]:
doctors.describe()

       doctor_id  department_id  experience_years
count    80.0000      80.000000         75.000000
mean   2040.5000     104.512500         11.586667
std      23.2379       2.354601          7.988325
min    2001.0000     101.000000          1.000000
25%    2020.7500     102.000000          4.000000
50%    2040.5000     105.000000         10.000000
75%    2060.2500     106.000000         20.000000
max    2080.0000     108.000000         24.000000

In [18]:
departments.describe()

       department_id  total_beds  available_beds  staff_count
count        8.00000    8.000000        8.000000     8.000000
mean       104.50000   32.500000       10.625000    36.125000
std          2.44949    9.258201        3.377975     9.372262
min        101.00000   20.000000        7.000000    24.000000
25%        102.75000   28.750000        8.750000    31.250000
50%        104.50000   30.000000       10.000000    34.500000
75%        106.25000   36.250000       11.250000    39.000000
max        108.00000   50.000000       18.000000    55.000000

In [19]:
admissions.describe()

        admission_id     patient_id    doctor_id  department_id
count    9000.000000    9000.000000  9000.000000    9000.000000
mean   404500.500000  105971.786000  2040.400333     104.528222
std      2598.220545    3475.760701    23.222364       2.338763
min    400001.000000  100001.000000  2001.000000     101.000000
25%    402250.750000  102929.750000  2020.000000     102.000000
50%    404500.500000  105924.000000  2040.000000     105.000000
75%    406750.250000  109022.000000  2061.000000     106.000000
max    409000.000000  112000.000000  2080.000000     108.000000

In [20]:
treatments.describe()

,treatment_id,admission_id,treatment_cost,treatment_duration_minutes
count,18000.000000,18000.000000,17920.000000,18000.000000
mean,509000.500000,404509.799056,3925.947773,76.786944
std,5196.296758,2607.400992,3407.971513,52.379599
min,500001.000000,400001.000000,250.000000,10.000000
25%,504500.750000,402253.000000,1806.312500,38.000000
50%,509000.500000,404483.000000,2966.620000,65.000000
75%,513500.250000,406783.000000,4929.580000,103.000000
max,518000.000000,408999.000000,54257.790000,360.000000

In [21]:
#Using Pandas Data cleaning 
#this is copy dataset

In [22]:
patients_clean = patients.copy()
doctors_clean = doctors.copy()
departments_clean = departments.copy()
appointments_clean = appointments.copy()
admissions_clean = admissions.copy()
treatments_clean = treatments.copy()

In [23]:
patients_clean.isnull().sum()

patient_id            0
patient_name          0
gender                0
date_of_birth         0
city                 60
state                 0
registration_date     0
insurance_type       35
dtype: int64

In [24]:
missing_percentage = (patients_clean.isnull().sum()/len(patients_clean))*10000

In [25]:
print(missing_percentage)

patient_id            0.000000
patient_name          0.000000
gender                0.000000
date_of_birth         0.000000
city                 49.937578
state                 0.000000
registration_date     0.000000
insurance_type       29.130254
dtype: float64

In [26]:
patients_clean.duplicated().sum()

np.int64(15)

In [27]:
patients_clean[patients_clean.duplicated()]

,patient_id,patient_name,gender,date_of_birth,city,state,registration_date,insurance_type
12000,109289,Patient_109289,Male,2013-11-27,Visakhapatnam,Andhra Pradesh,2024-01-03,Self-Pay
12001,108944,Patient_108944,Other,1984-09-04,New Delhi,Delhi,2024-12-25,Government
12002,111598,Patient_111598,Male,2021-08-15,Mysuru,Karnataka,2025-10-25,Self-Pay
12003,108658,Patient_108658,Female,1976-07-11,Madurai,Tamil Nadu,2025-07-11,Self-Pay
12004,103432,Patient_103432,Female,1990-06-09,Visakhapatnam,Andhra Pradesh,2025-12-07,Self-Pay
12005,107982,Patient_107982,Male,1997-08-23,Kochi,Kerala,2026-01-01,Private
12006,106173,Patient_106173,Male,1984-05-10,Madurai,Tamil Nadu,2026-01-21,Government
12007,111984,Patient_111984,Male,1966-09-03,Vijayawada,Andhra Pradesh,2024-07-02,Corporate
12008,101201,Patient_101201,Male,1965-04-07,Ahmedabad,Gujarat,2023-07-19,Corporate
12009,105324,Patient_105324,Male,2016-06-02,Trichy,Tamil Nadu,2025-06-15,Corporate
12010,101516,Patient_101516,Female,1993-04-22,Salem,Tamil Nadu,2025-04-16,Corporate
12011,102396,Patient_102396,Male,1980-04-30,Warangal,Telangana,2025-04-26,Private
12012,108043,Patient_108043,Female,1972-03-29,Madurai,Tamil Nadu,2023-05-27,Private
12013,107875,Patient_107875,Female,1991-03-28,Surat,Gujarat,2024-06-15,Private
12014,102495,Patient_102495,Male,2023-03-10,Ahmedabad,Gujarat,2023-11-11,Private

In [28]:
#handling missing value - patient_table

In [29]:
patients_clean = patients_clean.drop_duplicates()

In [30]:
patients_clean.duplicated().sum()

np.int64(0)

In [31]:
patients["city"].isnull().sum()

np.int64(60)

In [32]:
patients_clean["city"]=patients_clean["city"].fillna("unknown")

In [33]:
patients_clean["city"].isnull().sum()

np.int64(0)

In [34]:
patients_clean["insurance_type"]=patients_clean["insurance_type"].fillna("unknown")

In [35]:
patients_clean["insurance_type"].isnull().sum()

np.int64(0)

In [36]:
patients_clean.dtypes

patient_id           int64
patient_name           str
gender                 str
date_of_birth          str
city                   str
state                  str
registration_date      str
insurance_type         str
dtype: object

In [37]:
patients_clean["date_of_birth"] = pd.to_datetime(patients_clean["date_of_birth"])

In [38]:
patients_clean["registration_date "] = pd.to_datetime(patients_clean["registration_date"])

In [39]:
patients_clean.dtypes

patient_id                     int64
patient_name                     str
gender                           str
date_of_birth         datetime64[us]
city                             str
state                            str
registration_date                str
insurance_type                   str
registration_date     datetime64[us]
dtype: object

In [40]:
patients_clean["gender"].value_counts()

gender
Male      6119
Female    5740
Other      141
Name: count, dtype: int64

In [41]:
patients_clean["insurance_type"].value_counts()

insurance_type
Private       4524
Government    3310
Self-Pay      2644
Corporate     1487
unknown         35
Name: count, dtype: int64

In [42]:
patients_clean = patients.copy()
print(patients_clean.isnull().sum())
print("Dulicates:",patients_clean.duplicated().sum())
print(patients_clean.dtypes)
print(patients_clean.head())

patient_id            0
patient_name          0
gender                0
date_of_birth         0
city                 60
state                 0
registration_date     0
insurance_type       35
dtype: int64
Dulicates: 15
patient_id           int64
patient_name           str
gender                 str
date_of_birth          str
city                   str
state                  str
registration_date      str
insurance_type         str
dtype: object
   patient_id    patient_name  gender date_of_birth           city  \
0      100001  Patient_100001    Male    1966-05-04         Trichy
1      100002  Patient_100002    Male    2018-09-25         Mumbai
2      100003  Patient_100003    Male    2000-08-20  Visakhapatnam
3      100004  Patient_100004  Female    2000-10-31          Kochi
4      100005  Patient_100005  Female    1955-06-23      Hyderabad

            state registration_date insurance_type
0      Tamil Nadu        2024-09-09      Corporate
1     Maharashtra        2025-05-22        Private
2  Andhra Pradesh        2024-01-06        Private
3          Kerala        2025-03-12        Private
4       Telangana        2025-04-12     Government

In [43]:
# now clean a original dataset

In [44]:
patients_clean= patients_clean.drop_duplicates()

In [45]:
print("duplicates:",patients_clean.duplicated().sum())

duplicates: 0

In [46]:
print(patients_clean.shape)

(12000, 8)

In [47]:
patients_clean.isnull().sum()

patient_id            0
patient_name          0
gender                0
date_of_birth         0
city                 60
state                 0
registration_date     0
insurance_type       35
dtype: int64

In [48]:
patients_clean = patients.drop_duplicates().copy()
patients_clean["city"] = patients_clean["city"].fillna("Unknown")
patients_clean["insurance_type"] = patients_clean["insurance_type"].fillna("Unknown")

In [49]:
patients_clean["insurance_type"].value_counts()

insurance_type
Private       4524
Government    3310
Self-Pay      2644
Corporate     1487
Unknown         35
Name: count, dtype: int64

In [50]:
patients_clean["city"].value_counts()

city
New Delhi        1512
Mumbai            803
Pune              782
Kozhikode         766
Warangal          761
Vijayawada        760
Mysuru            735
Bengaluru         733
Surat             726
Ahmedabad         721
Hyderabad         717
Visakhapatnam     705
Kochi             705
Trichy            316
Salem             311
Coimbatore        298
Chennai           296
Madurai           293
Unknown            60
Name: count, dtype: int64

In [51]:
patients_clean.dtypes

patient_id           int64
patient_name           str
gender                 str
date_of_birth          str
city                   str
state                  str
registration_date      str
insurance_type         str
dtype: object

In [52]:
patients_clean["date_of_birth"] = pd.to_datetime(patients_clean["date_of_birth"])

In [53]:
patients_clean.dtypes

patient_id                    int64
patient_name                    str
gender                          str
date_of_birth        datetime64[us]
city                            str
state                           str
registration_date               str
insurance_type                  str
dtype: object

In [54]:
patients_clean["registration_date"] = pd.to_datetime(patients_clean["registration_date"])
patients_clean["date_of_birth"] = pd.to_datetime(patients_clean["date_of_birth"])

In [55]:
patients_clean.dtypes

patient_id                    int64
patient_name                    str
gender                          str
date_of_birth        datetime64[us]
city                            str
state                           str
registration_date    datetime64[us]
insurance_type                  str
dtype: object

In [56]:
patients_clean["gender"].value_counts()

gender
Male      6119
Female    5740
Other      141
Name: count, dtype: int64

In [57]:
patients_clean["insurance_type"].value_counts()

insurance_type
Private       4524
Government    3310
Self-Pay      2644
Corporate     1487
Unknown         35
Name: count, dtype: int64

In [58]:
print("minimum DOB:",patients_clean["date_of_birth"].min())
print("minimum DOB:",patients_clean["date_of_birth"].max())
print("minimum Reg:",patients_clean["registration_date"].min())
print("minimum Reg:",patients_clean["registration_date"].max())

minimum DOB: 1945-01-01 00:00:00
minimum DOB: 2024-12-24 00:00:00
minimum Reg: 2023-01-01 00:00:00
minimum Reg: 2026-06-30 00:00:00

In [59]:
print("rows:", patients_clean.shape[0])
print("columns:", patients_clean.shape[1])
print("Duplicated:", patients_clean.duplicated().sum())
print("\nmissind values:")
print(patients_clean.isnull().sum())

rows: 12000
columns: 8
Duplicated: 0

missind values:
patient_id           0
patient_name         0
gender               0
date_of_birth        0
city                 0
state                0
registration_date    0
insurance_type       0
dtype: int64

In [60]:
# data cleaning Doctors table

In [61]:
doctors_clean = doctors.copy()

In [62]:
print(doctors_clean.shape)

(80, 6)

In [63]:
print("Duplicates:", doctors_clean.duplicated().sum())

Duplicates: 0

In [64]:
doctors_clean.isnull().sum()

doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    5
employment_type     0
dtype: int64

In [65]:
doctors_clean.dtypes

doctor_id             int64
doctor_name             str
department_id         int64
specialization          str
experience_years    float64
employment_type         str
dtype: object

In [66]:
doctors_clean[doctors_clean["experience_years"].isnull()]

,doctor_id,doctor_name,department_id,specialization,experience_years,employment_type
3,2004,Dr_2004,101,Emergency Medicine,NaN,Full-Time
13,2014,Dr_2014,105,Pediatrics,NaN,Full-Time
19,2020,Dr_2020,102,Cardiology,NaN,Full-Time
32,2033,Dr_2033,105,Pediatrics,NaN,Contract
77,2078,Dr_2078,105,Pediatrics,NaN,Full-Time

In [67]:
med_value = doctors_clean["experience_years"].median()
doctors_clean["experience_years"]=doctors_clean["experience_years"].fillna(med_value)

In [68]:
doctors_clean.describe()

       doctor_id  department_id  experience_years
count    80.0000      80.000000         80.000000
mean   2040.5000     104.512500         11.487500
std      23.2379       2.354601          7.741052
min    2001.0000     101.000000          1.000000
25%    2020.7500     102.000000          4.750000
50%    2040.5000     105.000000         10.000000
75%    2060.2500     106.000000         20.000000
max    2080.0000     108.000000         24.000000

In [69]:
doctors_clean.isnull().sum()

doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    0
employment_type     0
dtype: int64

In [70]:
doctors_clean["experience_years"].max()

np.float64(24.0)

In [71]:
doctors_clean["department_id"].value_counts().sort_index()

department_id
101    11
102    12
103     5
104    10
105    11
106    12
107     8
108    11
Name: count, dtype: int64

In [72]:
print("row:",doctors_clean.shape[0])
print("column:",doctors_clean.shape[1])
print("Duplicates:",doctors_clean.duplicated().sum())
print("\n missing value")
print(doctors_clean.isnull().sum())

row: 80
column: 6
Duplicates: 0

 missing value
doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    0
employment_type     0
dtype: int64

In [73]:
# cleaning department table

In [74]:
departments_clean = departments.copy()

In [75]:
print(departments_clean.shape)

(8, 6)

In [76]:
print(departments_clean.isnull().sum())

department_id      0
department_name    0
department_type    0
total_beds         0
available_beds     0
staff_count        0
dtype: int64

In [77]:
print(departments_clean.duplicated().sum())

0

In [78]:
departments_clean.dtypes

department_id      int64
department_name      str
department_type      str
total_beds         int64
available_beds     int64
staff_count        int64
dtype: object

In [79]:
# checking bed avalability

In [80]:
departments_clean[["department_name","total_beds","available_beds"]]

    department_name  total_beds  available_beds
0         Emergency          40              12
1        Cardiology          35              10
2       Orthopedics          30               9
3         Neurology          25               7
4        Pediatrics          30              11
5  General Medicine          50              18
6       Dermatology          20               8
7        Gynecology          30              10

In [81]:
departments_clean[departments_clean["available_beds"]> departments_clean["total_beds"]]

Empty DataFrame
Columns: [department_id, department_name, department_type, total_beds, available_beds, staff_count]
Index: []

In [82]:
departments_clean[departments_clean["staff_count"]<=0]

Empty DataFrame
Columns: [department_id, department_name, department_type, total_beds, available_beds, staff_count]
Index: []

In [83]:
departments_clean["department_id"].value_counts()

department_id
101    1
102    1
103    1
104    1
105    1
106    1
107    1
108    1
Name: count, dtype: int64

In [84]:
# admission Table

In [85]:
appointments_clean = appointments.copy()
print(appointments_clean.shape)
print("\n mission value:")
print(appointments_clean.isnull().sum())
print("\n dup,licates value:")
print(appointments_clean.duplicated().sum())
appointments_clean.dtypes

(45000, 9)

 mission value:
appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes     120
satisfaction_score      9929
dtype: int64

 dup,licates value:
0

appointment_id            int64
patient_id                int64
doctor_id                 int64
appointment_date            str
appointment_time            str
appointment_type            str
appointment_status          str
waiting_time_minutes    float64
satisfaction_score      float64
dtype: object

In [86]:
appointments_clean.head(30)

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,appointment_type,appointment_status,waiting_time_minutes,satisfaction_score
0,300001,106888,2002,2025-02-06,08:00,Emergency,Completed,15.0,5.0
1,300002,101312,2010,2026-04-12,08:00,Consultation,No-Show,0.0,NaN
2,300003,104026,2061,2025-04-16,18:45,Consultation,Cancelled,0.0,NaN
3,300004,105386,2010,2026-04-04,14:00,Diagnostic,Completed,52.0,3.0
4,300005,102881,2062,2025-04-13,08:30,Diagnostic,Rescheduled,68.0,NaN
5,300006,111190,2038,2026-02-07,09:15,Emergency,Completed,51.0,4.0
6,300007,107647,2036,2025-04-19,12:15,Consultation,Completed,14.0,5.0
7,300008,111840,2051,2025-09-19,16:15,Emergency,Completed,44.0,5.0
8,300009,100599,2010,2025-03-01,11:45,Consultation,No-Show,0.0,NaN
9,300010,105918,2069,2026-06-30,08:45,Follow-Up,No-Show,0.0,NaN
10,300011,105009,2073,2025-07-08,08:30,Consultation,No-Show,0.0,NaN
11,300012,101807,2032,2026-04-27,16:30,Follow-Up,Completed,23.0,5.0
12,300013,107440,2010,2025-06-07,15:30,Follow-Up,Completed,67.0,5.0
13,300014,107043,2001,2025-06-16,15:00,Diagnostic,Completed,37.0,4.0
14,300015,106309,2038,2025-02-07,08:00,Consultation,Completed,45.0,3.0
15,300016,104903,2047,2025-05-22,19:00,Diagnostic,Completed,47.0,5.0
16,300017,111571,2040,2025-03-21,19:00,Follow-Up,Completed,49.0,4.0
17,300018,111125,2014,2025-07-04,17:30,Consultation,Completed,39.0,4.0
18,300019,108960,2006,2026-03-29,17:00,Consultation,No-Show,0.0,NaN
19,300020,100359,2006,2025-08-13,08:00,Consultation,Rescheduled,31.0,NaN
20,300021,108929,2070,2025-06-17,19:30,Consultation,No-Show,0.0,NaN
21,300022,109428,2079,2026-03-18,12:00,Follow-Up,Completed,10.0,4.0
22,300023,103252,2051,2025-01-16,10:15,Consultation,Completed,10.0,4.0
23,300024,106114,2056,2025-01-29,13:00,Diagnostic,Completed,47.0,5.0
24,300025,111872,2078,2026-01-27,13:30,Consultation,Completed,19.0,5.0
25,300026,105659,2045,2026-03-01,13:15,Consultation,Completed,28.0,4.0
26,300027,104960,2006,2026-02-23,12:30,Consultation,Cancelled,0.0,NaN
27,300028,107361,2018,2025-10-06,12:30,Follow-Up,Completed,22.0,4.0
28,300029,100325,2004,2026-02-28,14:15,Follow-Up,No-Show,0.0,NaN
29,300030,108785,2075,2026-02-10,19:15,Consultation,Completed,7.0,5.0

In [87]:
appointments_clean.groupby(
    "appointment_status"
)["satisfaction_score"].apply(
    lambda x: x.isnull().sum()
)

appointment_status
Cancelled      3527
Completed         0
No-Show        4048
Rescheduled    2354
Name: satisfaction_score, dtype: int64

In [88]:
appointments_clean["appointment_status"].value_counts()

appointment_status
Completed      35071
No-Show         4048
Cancelled       3527
Rescheduled     2354
Name: count, dtype: int64

In [89]:
appointments_clean.groupby(
    "appointment_status"
)["waiting_time_minutes"].apply(
    lambda x: x.isnull().sum()
)

appointment_status
Cancelled        5
Completed      104
No-Show          6
Rescheduled      5
Name: waiting_time_minutes, dtype: int64

In [90]:
appointments_clean[appointments_clean["waiting_time_minutes"].isnull()]["appointment_status"].value_counts()

appointment_status
Completed      104
No-Show          6
Rescheduled      5
Cancelled        5
Name: count, dtype: int64

In [91]:
appointments_clean.groupby("appointment_status")["waiting_time_minutes"].median()

appointment_status
Cancelled       0.0
Completed      29.0
No-Show         0.0
Rescheduled    29.0
Name: waiting_time_minutes, dtype: float64

In [92]:
appointments_clean["waiting_time_minutes"] = (
    appointments_clean.groupby("appointment_type")["waiting_time_minutes"]
    .transform(lambda x: x.fillna(x.median()))
)

In [93]:
print(appointments_clean.isnull().sum())

appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes       0
satisfaction_score      9929
dtype: int64

In [94]:
appointments_clean["waiting_time_minutes"].describe()

count    45000.000000
mean        28.753267
std         25.115296
min          0.000000
25%         10.000000
50%         24.000000
75%         42.000000
max        180.000000
Name: waiting_time_minutes, dtype: float64

In [95]:
appointments_clean["satisfaction_score"].describe()

count    35071.000000
mean         4.587038
std          0.582172
min          2.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: satisfaction_score, dtype: float64

In [96]:
print(appointments_clean["appointment_status"].value_counts())

appointment_status
Completed      35071
No-Show         4048
Cancelled       3527
Rescheduled     2354
Name: count, dtype: int64

In [380]:
print(
    appointments_clean[
        ~appointments_clean["appointment_status"].isin(
            ["Completed", "Cancelled", "No-Show", "Rescheduled"]
        )
    ]["appointment_status"].unique()
)

<StringArray>
[]
Length: 0, dtype: str

In [98]:
appointments_clean[(appointments_clean["satisfaction_score"]<1) | (appointments_clean["satisfaction_score"]>5)]

Empty DataFrame
Columns: [appointment_id, patient_id, doctor_id, appointment_date, appointment_time, appointment_type, appointment_status, waiting_time_minutes, satisfaction_score]
Index: []

In [99]:
appointments_clean["satisfaction_score"].value_counts().sort_index()

satisfaction_score
2.0       56
3.0     1524
4.0    11267
5.0    22224
Name: count, dtype: int64

In [100]:
print(appointments_clean["satisfaction_score"].max())
print(appointments_clean["satisfaction_score"].min())
print(appointments_clean[appointments_clean["satisfaction_score"].isin(["1","2","3","4","5"])]["satisfaction_score"].unique())

5.0
2.0
[]

In [101]:
appointments_clean["waiting_time_minutes"].describe()

count    45000.000000
mean        28.753267
std         25.115296
min          0.000000
25%         10.000000
50%         24.000000
75%         42.000000
max        180.000000
Name: waiting_time_minutes, dtype: float64

In [102]:
q1 = appointments_clean["waiting_time_minutes"].quantile(0.25)
q2 = appointments_clean["waiting_time_minutes"].quantile(0.75)
IQR = q2 - q1
lower_limit = q1 - 1.5*IQR
upper_limit = q2 + 1.5*IQR
print("Q1:",q1)
print("Q2:",q2)
print("IQR:",IQR)
print("lower_limit:",lower_limit)
print("upper_limit:",upper_limit)

Q1: 10.0
Q2: 42.0
IQR: 32.0
lower_limit: -38.0
upper_limit: 90.0

In [103]:
outlier = appointments_clean[(appointments_clean["waiting_time_minutes"]<lower_limit) | (appointments_clean["waiting_time_minutes"]>upper_limit)]
print("Number of outlier:", outlier)

Number of outlier:        appointment_id  patient_id  doctor_id appointment_date  \
86             300087      109042       2029       2026-06-17
163            300164      103632       2035       2026-04-04
180            300181      107358       2002       2025-08-03
186            300187      101213       2021       2026-03-07
252            300253      102252       2066       2025-07-18
...               ...         ...        ...              ...
44937          344938      102670       2070       2026-04-21
44939          344940      109799       2012       2025-10-30
44942          344943      102885       2024       2025-02-09
44967          344968      111130       2071       2025-08-18
44990          344991      110929       2029       2026-04-09

      appointment_time appointment_type appointment_status  \
86               12:30     Consultation          Completed
163              17:45        Follow-Up        Rescheduled
180              12:15     Consultation          Completed
186              09:30     Consultation          Completed
252              12:45        Emergency          Completed
...                ...              ...                ...
44937            11:30       Diagnostic          Completed
44939            12:00        Follow-Up          Completed
44942            14:00     Consultation          Completed
44967            17:45     Consultation          Completed
44990            12:30        Follow-Up          Completed

       waiting_time_minutes  satisfaction_score
86                    111.0                 4.0
163                   109.0                 NaN
180                   138.0                 4.0
186                    91.0                 4.0
252                   110.0                 3.0
...                     ...                 ...
44937                 109.0                 3.0
44939                  92.0                 4.0
44942                 104.0                 4.0
44967                 105.0                 4.0
44990                  96.0                 3.0

[1139 rows x 9 columns]

In [382]:
appointments_clean["waiting_time_outlier"] = (
    appointments_clean["waiting_time_minutes"] > upper_limit
)

print(appointments_clean["waiting_time_outlier"].value_counts())

waiting_time_outlier
True     33864
False    11136
Name: count, dtype: int64

In [105]:
print(appointments_clean.dtypes)

appointment_id            int64
patient_id                int64
doctor_id                 int64
appointment_date            str
appointment_time            str
appointment_type            str
appointment_status          str
waiting_time_minutes    float64
satisfaction_score      float64
waiting_time_outlier       bool
dtype: object

In [106]:
appointments_clean = appointments_clean.drop(columns=["waiting_time_outlier"])

In [107]:
appointments_clean["appointment_date"]= pd.to_datetime(appointments_clean["appointment_date"])

In [108]:
print(appointments_clean.shape)
print(appointments_clean.dtypes)

(45000, 9)
appointment_id                   int64
patient_id                       int64
doctor_id                        int64
appointment_date        datetime64[us]
appointment_time                   str
appointment_type                   str
appointment_status                 str
waiting_time_minutes           float64
satisfaction_score             float64
dtype: object

In [109]:
print(appointments_clean["appointment_time"].head())
print(appointments_clean["appointment_time"].isnull().sum())

0    08:00
1    08:00
2    18:45
3    14:00
4    08:30
Name: appointment_time, dtype: str
0

In [110]:
appointments_clean["appointment_time"] = pd.to_datetime(appointments_clean["appointment_time"],format = "%H:%M").dt.time

In [111]:
print(appointments_clean["appointment_time"].head())
print(appointments_clean["appointment_time"].dtypes)

0    08:00:00
1    08:00:00
2    18:45:00
3    14:00:00
4    08:30:00
Name: appointment_time, dtype: object
object

In [112]:
print(appointments_clean["appointment_time"].value_counts())
print()
print(appointments_clean["appointment_status"].value_counts())

appointment_time
12:30:00    979
09:30:00    978
19:30:00    976
12:45:00    976
14:00:00    968
11:00:00    968
08:30:00    965
08:45:00    965
10:15:00    964
13:00:00    963
16:30:00    959
18:15:00    959
17:45:00    956
19:00:00    955
17:15:00    955
19:45:00    953
09:00:00    952
09:15:00    949
10:45:00    947
10:30:00    946
18:00:00    943
14:15:00    941
19:15:00    939
15:15:00    939
14:30:00    937
16:45:00    936
13:45:00    932
08:00:00    931
18:45:00    931
12:15:00    930
18:30:00    930
16:00:00    929
12:00:00    927
14:45:00    927
11:30:00    924
11:45:00    923
11:15:00    921
17:30:00    919
13:30:00    915
15:00:00    913
09:45:00    913
08:15:00    910
15:45:00    909
13:15:00    908
10:00:00    901
17:00:00    898
15:30:00    880
16:15:00    861
Name: count, dtype: int64

appointment_status
Completed      35071
No-Show         4048
Cancelled       3527
Rescheduled     2354
Name: count, dtype: int64

In [113]:
print("Duplicates:",appointments_clean.duplicated().sum())

Duplicates: 0

In [114]:
print(appointments_clean.isnull().sum())

appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes       0
satisfaction_score      9929
dtype: int64

In [115]:
print(appointments_clean.describe())

       appointment_id     patient_id     doctor_id  \
count    45000.000000   45000.000000  45000.000000
mean    322500.500000  105963.671978   2040.595822
min     300001.000000  100001.000000   2001.000000
25%     311250.750000  102950.500000   2021.000000
50%     322500.500000  105965.000000   2041.000000
75%     333750.250000  108950.000000   2061.000000
max     345000.000000  112000.000000   2080.000000
std      12990.525394    3463.644253     23.128890

                 appointment_date  waiting_time_minutes  satisfaction_score
count                       45000          45000.000000        35071.000000
mean   2025-09-30 13:27:48.480000             28.753267            4.587038
min           2025-01-01 00:00:00              0.000000            2.000000
25%           2025-05-18 00:00:00             10.000000            4.000000
50%           2025-09-30 00:00:00             24.000000            5.000000
75%           2026-02-13 00:00:00             42.000000            5.000000
max           2026-06-30 00:00:00            180.000000            5.000000
std                           NaN             25.115296            0.582172

In [116]:
print(appointments_clean["satisfaction_score"].value_counts().sort_index())

satisfaction_score
2.0       56
3.0     1524
4.0    11267
5.0    22224
Name: count, dtype: int64

In [117]:
print(appointments_clean.groupby("appointment_status")["satisfaction_score"].agg(["count","mean","median"]))
print(appointments_clean.groupby("appointment_status")["satisfaction_score"].count())
print(appointments_clean.groupby("appointment_status")["satisfaction_score"].median())

                    count      mean  median
appointment_status
Cancelled               0       NaN     NaN
Completed           35071  4.587038     5.0
No-Show                 0       NaN     NaN
Rescheduled             0       NaN     NaN
appointment_status
Cancelled          0
Completed      35071
No-Show            0
Rescheduled        0
Name: satisfaction_score, dtype: int64
appointment_status
Cancelled      NaN
Completed      5.0
No-Show        NaN
Rescheduled    NaN
Name: satisfaction_score, dtype: float64

In [118]:
print(appointments_clean["satisfaction_score"].value_counts(dropna=False).sort_index())
print(appointments_clean[
    (appointments_clean["satisfaction_score"] < 1) |
    (appointments_clean["satisfaction_score"] > 5)
]["satisfaction_score"].value_counts())

satisfaction_score
2.0       56
3.0     1524
4.0    11267
5.0    22224
NaN     9929
Name: count, dtype: int64
Series([], Name: count, dtype: int64)

In [119]:
print(appointments_clean["waiting_time_minutes"].isnull().sum())
print((appointments_clean["waiting_time_minutes"]<0).sum())
print(appointments_clean["waiting_time_minutes"].describe())

0
0
count    45000.000000
mean        28.753267
std         25.115296
min          0.000000
25%         10.000000
50%         24.000000
75%         42.000000
max        180.000000
Name: waiting_time_minutes, dtype: float64

In [120]:
print(appointments_clean["satisfaction_score"].isnull().sum())

9929

In [121]:
print(appointments_clean.isnull().sum())
print(appointments_clean.dtypes)
print(appointments_clean.shape)
print(appointments_clean.duplicated().sum())

appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes       0
satisfaction_score      9929
dtype: int64
appointment_id                   int64
patient_id                       int64
doctor_id                        int64
appointment_date        datetime64[us]
appointment_time                object
appointment_type                   str
appointment_status                 str
waiting_time_minutes           float64
satisfaction_score             float64
dtype: object
(45000, 9)
0

In [122]:
#Admission table cleaning

In [123]:
admissions_clean = admissions.copy()

In [124]:
print(admissions_clean.shape)
print("\nnull value:")
print(admissions_clean.isnull().sum())
print("Duplicates:",admissions_clean.duplicated().sum())
print(admissions_clean.dtypes)

(9000, 10)

null value:
admission_id        0
patient_id          0
doctor_id           0
department_id       0
admission_date      0
discharge_date      0
admission_type      0
bed_number          0
admission_status    0
readmission_flag    0
dtype: int64
Duplicates: 0
admission_id        int64
patient_id          int64
doctor_id           int64
department_id       int64
admission_date        str
discharge_date        str
admission_type        str
bed_number            str
admission_status      str
readmission_flag     bool
dtype: object

In [125]:
admissions_clean["admission_date"] = pd.to_datetime(admissions_clean["admission_date"])

In [126]:
admissions_clean["discharge_date"] = pd.to_datetime(admissions_clean["discharge_date"])

In [127]:
print(admissions_clean.dtypes)

admission_id                 int64
patient_id                   int64
doctor_id                    int64
department_id                int64
admission_date      datetime64[us]
discharge_date      datetime64[us]
admission_type                 str
bed_number                     str
admission_status               str
readmission_flag              bool
dtype: object

In [128]:
print((admissions_clean["discharge_date"]<admissions_clean["admission_date"]).sum())
print(admissions_clean[admissions_clean["discharge_date"]<admissions_clean["admission_date"]][["admission_date","discharge_date"]].head())

0
Empty DataFrame
Columns: [admission_date, discharge_date]
Index: []

In [129]:
print(admissions_clean["bed_number"].value_counts().head(20))

bed_number
101-47    40
108-35    39
101-20    38
102-10    37
105-46    37
105-09    36
104-27    36
106-03    36
106-05    36
108-22    35
105-31    35
102-18    35
106-34    35
105-36    34
106-45    33
108-34    33
106-07    33
102-16    33
101-09    33
101-22    33
Name: count, dtype: int64

In [130]:
print(admissions_clean["bed_number"].unique())

<StringArray>
['102-03', '106-27', '105-41', '102-01', '101-24', '101-40', '105-36',
 '107-32', '106-45', '107-17',
 ...
 '105-19', '107-06', '107-09', '105-35', '102-20', '104-06', '103-26',
 '107-48', '103-27', '103-29']
Length: 400, dtype: str

In [131]:
print(admissions_clean["admission_type"].value_counts())
print(admissions_clean["admission_status"].value_counts())
print(admissions_clean["readmission_flag"].value_counts())

admission_type
Elective     4980
Emergency    2673
Referral     1347
Name: count, dtype: int64
admission_status
Discharged         7756
Transferred         727
Under Treatment     517
Name: count, dtype: int64
readmission_flag
False    8176
True      824
Name: count, dtype: int64

In [132]:
print(admissions_clean["admission_type"].unique())
print(admissions_clean["admission_status"].unique())
print(admissions_clean["readmission_flag"].unique())

<StringArray>
['Elective', 'Referral', 'Emergency']
Length: 3, dtype: str
<StringArray>
['Discharged', 'Under Treatment', 'Transferred']
Length: 3, dtype: str
[False  True]

In [133]:
print((admissions_clean["discharge_date"]<admissions_clean["admission_date"]).sum())
admissions_clean["length_of_stay"] = (admissions_clean["discharge_date"] - admissions_clean["admission_date"]).dt.days
print(admissions_clean["length_of_stay"].describe())

0
count    9000.000000
mean        4.013889
std         2.828256
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        25.000000
Name: length_of_stay, dtype: float64

In [134]:
print(admissions_clean["length_of_stay"].head(20))
print((admissions_clean["length_of_stay"]<0).sum())

0     4
1     4
2     3
3     3
4     4
5     2
6     5
7     4
8     3
9     6
10    3
11    7
12    3
13    4
14    3
15    5
16    7
17    6
18    6
19    2
Name: length_of_stay, dtype: int64
0

In [135]:
q1 = admissions_clean["length_of_stay"].quantile(0.25)
q2 = admissions_clean["length_of_stay"].quantile(0.75)
IQR = q2 - q1
lower = q1 - 1.5*IQR
upper = q2 + 1.5*IQR
print(q1)
print(q2)
print(IQR)
print(lower)
print(upper)

2.0
5.0
3.0
-2.5
9.5

In [136]:
print("outlier:",((admissions_clean["length_of_stay"] < lower) | (admissions_clean["length_of_stay"] > upper)).sum())

outlier: 442

In [137]:
print("Missing bed numbers:",
      admissions_clean["bed_number"].isnull().sum())

print("Unique bed numbers:",
      admissions_clean["bed_number"].nunique())

print("Bed number format:")
print(admissions_clean["bed_number"].head(20))

Missing bed numbers: 0
Unique bed numbers: 400
Bed number format:
0     102-03
1     106-27
2     105-41
3     102-01
4     101-24
5     101-40
6     105-36
7     107-32
8     106-45
9     107-17
10    106-22
11    102-47
12    101-47
13    108-47
14    101-24
15    106-24
16    108-13
17    107-26
18    103-46
19    101-26
Name: bed_number, dtype: str

In [138]:
print("Shape:", admissions_clean.shape)

print("\nMissing values:")
print(admissions_clean.isnull().sum())

print("\nDuplicates:", admissions_clean.duplicated().sum())

print("\nData types:")
print(admissions_clean.dtypes)

Shape: (9000, 11)

Missing values:
admission_id        0
patient_id          0
doctor_id           0
department_id       0
admission_date      0
discharge_date      0
admission_type      0
bed_number          0
admission_status    0
readmission_flag    0
length_of_stay      0
dtype: int64

Duplicates: 0

Data types:
admission_id                 int64
patient_id                   int64
doctor_id                    int64
department_id                int64
admission_date      datetime64[us]
discharge_date      datetime64[us]
admission_type                 str
bed_number                     str
admission_status               str
readmission_flag              bool
length_of_stay               int64
dtype: object

In [139]:
print(patients_clean.shape)
print(patients_clean.isnull().sum())
print(patients_clean.duplicated().sum())
print(patients_clean.dtypes)

(12000, 8)
patient_id           0
patient_name         0
gender               0
date_of_birth        0
city                 0
state                0
registration_date    0
insurance_type       0
dtype: int64
0
patient_id                    int64
patient_name                    str
gender                          str
date_of_birth        datetime64[us]
city                            str
state                           str
registration_date    datetime64[us]
insurance_type                  str
dtype: object

In [140]:
treatments_clean = treatments.copy()

print(treatments_clean.shape)
print(treatments_clean.isnull().sum())
print("Duplicates:", treatments_clean.duplicated().sum())
print(treatments_clean.dtypes)

(18000, 8)
treatment_id                   0
admission_id                   0
treatment_date                 0
diagnosis                      0
treatment_type                 0
treatment_cost                80
treatment_duration_minutes     0
treatment_outcome              0
dtype: int64
Duplicates: 0
treatment_id                    int64
admission_id                    int64
treatment_date                    str
diagnosis                         str
treatment_type                    str
treatment_cost                float64
treatment_duration_minutes      int64
treatment_outcome                 str
dtype: object

In [141]:
print(treatments_clean["treatment_cost"].describe())
print()
print(treatments_clean["treatment_cost"].value_counts().head(20))

count    17920.000000
mean      3925.947773
std       3407.971513
min        250.000000
25%       1806.312500
50%       2966.620000
75%       4929.580000
max      54257.790000
Name: treatment_cost, dtype: float64

treatment_cost
250.00     7
1529.22    2
2604.43    2
1905.79    2
3390.88    2
1973.61    2
1986.64    2
1094.70    2
1072.95    2
667.07     2
4326.65    2
1697.94    2
2316.21    2
3301.04    2
2004.60    2
4504.00    2
934.14     2
1913.33    2
1839.79    2
1751.66    2
Name: count, dtype: int64

In [142]:
treatments_clean["treatment_cost"] = treatments_clean["treatment_cost"].fillna(
    treatments_clean["treatment_cost"].median()
)

In [143]:
print(treatments_clean["treatment_cost"].isnull().sum())
print(treatments_clean["treatment_cost"].median())

0
2966.62

In [144]:
print(treatments_clean.dtypes)

treatment_id                    int64
admission_id                    int64
treatment_date                    str
diagnosis                         str
treatment_type                    str
treatment_cost                float64
treatment_duration_minutes      int64
treatment_outcome                 str
dtype: object

In [145]:
treatments_clean["treatment_date"] = pd.to_datetime(treatments_clean["treatment_date"])

In [146]:
print(treatments_clean["treatment_duration_minutes"].describe())

count    18000.000000
mean        76.786944
std         52.379599
min         10.000000
25%         38.000000
50%         65.000000
75%        103.000000
max        360.000000
Name: treatment_duration_minutes, dtype: float64

In [147]:
Q1 = treatments_clean["treatment_duration_minutes"].quantile(0.25)
Q3 = treatments_clean["treatment_duration_minutes"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower)
print("Upper limit:", upper)

print(
    "Outliers:",
    (
        (treatments_clean["treatment_duration_minutes"] < lower) |
        (treatments_clean["treatment_duration_minutes"] > upper)
    ).sum()
)

Q1: 38.0
Q3: 103.0
IQR: 65.0
Lower limit: -59.5
Upper limit: 200.5
Outliers: 541

In [148]:
Q1 = treatments_clean["treatment_cost"].quantile(0.25)
Q3 = treatments_clean["treatment_cost"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower)
print("Upper limit:", upper)

print(
    "Outliers:",
    (
        (treatments_clean["treatment_cost"] < lower) |
        (treatments_clean["treatment_cost"] > upper)
    ).sum()
)

Q1: 1811.6175
Q3: 4917.7575
IQR: 3106.1399999999994
Lower limit: -2847.592499999999
Upper limit: 9576.967499999999
Outliers: 1015

In [149]:
print("Treatment Type:")
print(treatments_clean["treatment_type"].value_counts())

print("\nTreatment Outcome:")
print(treatments_clean["treatment_outcome"].value_counts())

print("\nDiagnosis:")
print(treatments_clean["diagnosis"].value_counts().head(20))

Treatment Type:
treatment_type
Medication         5458
Diagnostic Test    3516
Procedure          2899
Therapy            2153
Consultation       2119
Surgery            1855
Name: count, dtype: int64

Treatment Outcome:
treatment_outcome
Improved        12213
Stable           3620
Referred         1451
Complication      716
Name: count, dtype: int64

Diagnosis:
diagnosis
Infection            1870
Cardiac Issue        1844
Pregnancy-related    1819
Other                1813
Skin Condition       1811
Diabetes             1794
Migraine             1779
Asthma               1771
Fracture             1750
Hypertension         1749
Name: count, dtype: int64

In [150]:
invalid_admissions = ~treatments_clean["admission_id"].isin(
    admissions_clean["admission_id"]
)

print("Invalid admission IDs:", invalid_admissions.sum())

Invalid admission IDs: 0

In [151]:
invaild_treatment_id =  (treatments_clean["treatment_date"]<
                       admissions_clean.set_index("admission_id")
                           .loc[treatments_clean["admission_id"],"admission_date"].values) | (treatments_clean["treatment_date"]>
                       admissions_clean.set_index("admission_id")
                        .loc[treatments_clean["admission_id"],"discharge_date"].values)

In [152]:
print(invaild_treatment_id.sum())

5108

In [153]:
admission_lookup = admissions_clean.set_index("admission_id")
treatment_check = treatments_clean.copy()
treatment_check["admission_date"] = treatment_check["admission_id"].map(
    admission_lookup["admission_date"]
)
treatment_check["discharge_date"] = treatment_check["admission_id"].map(
    admission_lookup["discharge_date"]
)
print(
    treatment_check[
        treatment_check["treatment_date"] < treatment_check["admission_date"]
    ][["admission_id", "treatment_date", "admission_date", "discharge_date"]].head(10)
)

Empty DataFrame
Columns: [admission_id, treatment_date, admission_date, discharge_date]
Index: []

In [154]:
print(
    "Before admission:",
    (treatment_check["treatment_date"] < treatment_check["admission_date"]).sum()
)

print(
    "After discharge:",
    (treatment_check["treatment_date"] > treatment_check["discharge_date"]).sum()
)

Before admission: 0
After discharge: 5108

In [155]:
admission_dates = admissions_clean.set_index("admission_id")

invalid_treatments = treatments_clean[
    (treatments_clean["treatment_date"] <
     admission_dates.loc[treatments_clean["admission_id"], "admission_date"].values)
    |
    (treatments_clean["treatment_date"] >
     admission_dates.loc[treatments_clean["admission_id"], "discharge_date"].values)
]

print("Invalid treatments:", len(invalid_treatments))

print(invalid_treatments[
    ["treatment_id", "admission_id", "treatment_date"]
].head(20))

Invalid treatments: 5108
    treatment_id  admission_id treatment_date
8         500009        406197     2026-02-20
15        500016        404675     2026-02-19
17        500018        405815     2026-04-07
24        500025        406635     2025-09-15
26        500027        406424     2025-11-30
28        500029        408932     2025-10-21
29        500030        407588     2025-10-29
31        500032        404241     2026-03-07
32        500033        400709     2025-01-25
40        500041        408080     2025-04-12
44        500045        404468     2026-04-14
49        500050        403926     2025-06-18
53        500054        400114     2025-08-12
57        500058        407265     2025-04-18
61        500062        408129     2025-04-18
64        500065        401726     2025-08-15
67        500068        400874     2025-11-26
68        500069        403742     2025-10-12
69        500070        401225     2025-08-10
78        500079        407147     2026-03-25

In [156]:
print(
    invalid_treatments[
        ["treatment_id", "admission_id", "treatment_date"]
    ].head(20)
)

    treatment_id  admission_id treatment_date
8         500009        406197     2026-02-20
15        500016        404675     2026-02-19
17        500018        405815     2026-04-07
24        500025        406635     2025-09-15
26        500027        406424     2025-11-30
28        500029        408932     2025-10-21
29        500030        407588     2025-10-29
31        500032        404241     2026-03-07
32        500033        400709     2025-01-25
40        500041        408080     2025-04-12
44        500045        404468     2026-04-14
49        500050        403926     2025-06-18
53        500054        400114     2025-08-12
57        500058        407265     2025-04-18
61        500062        408129     2025-04-18
64        500065        401726     2025-08-15
67        500068        400874     2025-11-26
68        500069        403742     2025-10-12
69        500070        401225     2025-08-10
78        500079        407147     2026-03-25

In [157]:
invalid_check = invalid_treatments.copy()

invalid_check["discharge_date"] = invalid_check["admission_id"].map(
    admissions_clean.set_index("admission_id")["discharge_date"]
)

print(
    invalid_check[
        ["treatment_id", "admission_id", "treatment_date", "discharge_date"]
    ].head(20)
)

    treatment_id  admission_id treatment_date discharge_date
8         500009        406197     2026-02-20     2026-02-19
15        500016        404675     2026-02-19     2026-02-17
17        500018        405815     2026-04-07     2026-04-05
24        500025        406635     2025-09-15     2025-09-13
26        500027        406424     2025-11-30     2025-11-27
28        500029        408932     2025-10-21     2025-10-20
29        500030        407588     2025-10-29     2025-10-28
31        500032        404241     2026-03-07     2026-03-06
32        500033        400709     2025-01-25     2025-01-24
40        500041        408080     2025-04-12     2025-04-11
44        500045        404468     2026-04-14     2026-04-12
49        500050        403926     2025-06-18     2025-06-15
53        500054        400114     2025-08-12     2025-08-11
57        500058        407265     2025-04-18     2025-04-15
61        500062        408129     2025-04-18     2025-04-16
64        500065        401726     2025-08-15     2025-08-13
67        500068        400874     2025-11-26     2025-11-25
68        500069        403742     2025-10-12     2025-10-11
69        500070        401225     2025-08-10     2025-08-09
78        500079        407147     2026-03-25     2026-03-22

In [158]:
treatments_clean = treatments_clean.drop(invalid_check.index)

print("Shape after removing invalid treatments:", treatments_clean.shape)
print("Invalid treatment dates remaining:", len(invalid_check))

Shape after removing invalid treatments: (12892, 8)
Invalid treatment dates remaining: 5108

In [159]:
admission_dates = admissions_clean.set_index("admission_id")

invalid_after_cleaning = (
    (treatments_clean["treatment_date"] <
     admission_dates.loc[treatments_clean["admission_id"], "admission_date"].values)
    |
    (treatments_clean["treatment_date"] >
     admission_dates.loc[treatments_clean["admission_id"], "discharge_date"].values)
)

print("Invalid treatment dates after cleaning:", invalid_after_cleaning.sum())

Invalid treatment dates after cleaning: 0

In [160]:
print(treatments_clean.shape)
print(treatments_clean.isnull().sum())
print(treatments_clean.duplicated().sum())
print(treatments_clean.dtypes)

(12892, 8)
treatment_id                  0
admission_id                  0
treatment_date                0
diagnosis                     0
treatment_type                0
treatment_cost                0
treatment_duration_minutes    0
treatment_outcome             0
dtype: int64
0
treatment_id                           int64
admission_id                           int64
treatment_date                datetime64[us]
diagnosis                                str
treatment_type                           str
treatment_cost                       float64
treatment_duration_minutes             int64
treatment_outcome                        str
dtype: object

In [161]:
import os
os.makedirs("cleaned_data",exist_ok =True)

In [162]:
patients_clean.to_csv("cleaned_data/patients_clean.csv", index=False)
admissions_clean.to_csv("cleaned_data/admissions_clean.csv", index=False)
treatments_clean.to_csv("cleaned_data/treatments_clean.csv", index=False)
appointments_clean.to_csv("cleaned_data/appointments_clean.csv", index=False)
doctors_clean.to_csv("cleaned_data/doctors_clean.csv", index=False)
departments_clean.to_csv("cleaned_data/departments_clean.csv", index=False)

print("All 6 cleaned tables saved successfully!")
print(os.listdir("cleaned_data"))

All 6 cleaned tables saved successfully!
['.ipynb_checkpoints', 'admissions_clean.csv', 'appointments_clean.csv', 'departments_clean.csv', 'doctors_clean.csv', 'patients_clean.csv', 'treatments_clean.csv']

In [163]:
# EDA for Doctors table

In [164]:
print("Doctors Shape:", doctors_clean.shape)

print("\nDoctors Missing Values:")
print(doctors_clean.isnull().sum())

print("\nDoctors Duplicates:")
print(doctors_clean.duplicated().sum())

print("\nDoctors Data Types:")
print(doctors_clean.dtypes)

print("\nDoctors Preview:")
print(doctors_clean.head())

Doctors Shape: (80, 6)

Doctors Missing Values:
doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    0
employment_type     0
dtype: int64

Doctors Duplicates:
0

Doctors Data Types:
doctor_id             int64
doctor_name             str
department_id         int64
specialization          str
experience_years    float64
employment_type         str
dtype: object

Doctors Preview:
   doctor_id doctor_name  department_id      specialization  experience_years  \
0       2001     Dr_2001            102          Cardiology               8.0
1       2002     Dr_2002            107         Dermatology               1.0
2       2003     Dr_2003            103         Orthopedics               8.0
3       2004     Dr_2004            101  Emergency Medicine              10.0
4       2005     Dr_2005            106    General Medicine              21.0

  employment_type
0       Full-Time
1       Part-Time
2       Full-Time
3       Full-Time
4       Full-Time

In [165]:
print("Specialization:")
print(doctors_clean["specialization"].value_counts())

print("\nEmployment Type:")
print(doctors_clean["employment_type"].value_counts())

print("\nExperience Statistics:")
print(doctors_clean["experience_years"].describe())

print("\nDoctors per Department:")
print(doctors_clean["department_id"].value_counts().sort_index())

Specialization:
specialization
Cardiology            12
General Medicine      12
Emergency Medicine    11
Pediatrics            11
Gynecology            11
Neurology             10
Dermatology            8
Orthopedics            5
Name: count, dtype: int64

Employment Type:
employment_type
Full-Time    58
Part-Time    12
Contract     10
Name: count, dtype: int64

Experience Statistics:
count    80.000000
mean     11.487500
std       7.741052
min       1.000000
25%       4.750000
50%      10.000000
75%      20.000000
max      24.000000
Name: experience_years, dtype: float64

Doctors per Department:
department_id
101    11
102    12
103     5
104    10
105    11
106    12
107     8
108    11
Name: count, dtype: int64

In [166]:
doctors_clean.groupby("specialization")["experience_years"].agg(["count","min","max","mean"]).sort_values("mean",ascending = False)

                    count  min   max       mean
specialization
Cardiology             12  1.0  24.0  13.083333
General Medicine       12  1.0  23.0  12.583333
Neurology              10  1.0  24.0  11.400000
Emergency Medicine     11  2.0  24.0  11.363636
Pediatrics             11  1.0  21.0  11.272727
Gynecology             11  1.0  23.0  11.000000
Dermatology             8  1.0  21.0  10.125000
Orthopedics             5  2.0  23.0   9.200000

In [167]:
doctors_clean.groupby("employment_type")["experience_years"].agg(["count","min","max","mean"]).sort_values("mean",ascending = False)

                 count  min   max       mean
employment_type
Part-Time           12  1.0  23.0  13.666667
Full-Time           58  1.0  24.0  11.379310
Contract            10  2.0  23.0   9.500000

In [168]:
# EDA for Department table

In [169]:
print("Departments Shape:", departments_clean.shape)

print("\nDepartments Missing Values:")
print(departments_clean.isnull().sum())

print("\nDepartments Duplicates:")
print(departments_clean.duplicated().sum())

print("\nDepartments Data Types:")
print(departments_clean.dtypes)

print("\nDepartments Preview:")
print(departments_clean.head())

Departments Shape: (8, 6)

Departments Missing Values:
department_id      0
department_name    0
department_type    0
total_beds         0
available_beds     0
staff_count        0
dtype: int64

Departments Duplicates:
0

Departments Data Types:
department_id      int64
department_name      str
department_type      str
total_beds         int64
available_beds     int64
staff_count        int64
dtype: object

Departments Preview:
   department_id department_name department_type  total_beds  available_beds  \
0            101       Emergency       Emergency          40              12
1            102      Cardiology       Specialty          35              10
2            103     Orthopedics       Specialty          30               9
3            104       Neurology       Specialty          25               7
4            105      Pediatrics       Specialty          30              11

   staff_count
0           42
1           38
2           32
3           29
4           35

In [170]:
print("Department Names:", departments_clean["department_type"].value_counts())

Department Names: department_type
Specialty    6
Emergency    1
General      1
Name: count, dtype: int64

In [171]:
departments_clean[departments_clean["available_beds"] > departments_clean["total_beds"]]

Empty DataFrame
Columns: [department_id, department_name, department_type, total_beds, available_beds, staff_count]
Index: []

In [172]:
print(departments_clean.columns)

Index(['department_id', 'department_name', 'department_type', 'total_beds',
       'available_beds', 'staff_count'],
      dtype='str')

In [173]:
print("Department Types:", departments_clean["department_type"].value_counts())

Department Types: department_type
Specialty    6
Emergency    1
General      1
Name: count, dtype: int64

In [174]:
print(departments_clean["total_beds"].describe())
print(departments_clean["available_beds"].describe())
print(departments_clean["staff_count"].describe())

count     8.000000
mean     32.500000
std       9.258201
min      20.000000
25%      28.750000
50%      30.000000
75%      36.250000
max      50.000000
Name: total_beds, dtype: float64
count     8.000000
mean     10.625000
std       3.377975
min       7.000000
25%       8.750000
50%      10.000000
75%      11.250000
max      18.000000
Name: available_beds, dtype: float64
count     8.000000
mean     36.125000
std       9.372262
min      24.000000
25%      31.250000
50%      34.500000
75%      39.000000
max      55.000000
Name: staff_count, dtype: float64

In [175]:
departments_clean.head()

,department_id,department_name,department_type,total_beds,available_beds,staff_count
0,101,Emergency,Emergency,40,12,42
1,102,Cardiology,Specialty,35,10,38
2,103,Orthopedics,Specialty,30,9,32
3,104,Neurology,Specialty,25,7,29
4,105,Pediatrics,Specialty,30,11,35

In [176]:
invalid_beds = departments_clean[departments_clean["available_beds"] > departments_clean["total_beds"]]
print(len(invalid_beds))
print(invalid_beds[["department_id","department_name","total_beds","available_beds"]])

0
Empty DataFrame
Columns: [department_id, department_name, total_beds, available_beds]
Index: []

In [177]:
departments_clean["occupied_bed"] = (departments_clean["total_beds"] - departments_clean["available_beds"])
departments_clean["occupancy_rate"] = (departments_clean["occupied_bed"] / departments_clean["total_beds"]*100)

print(departments_clean[["department_name","total_beds","available_beds","occupied_bed","occupancy_rate"]].sort_values("occupancy_rate",ascending= False))

    department_name  total_beds  available_beds  occupied_bed  occupancy_rate
3         Neurology          25               7            18       72.000000
1        Cardiology          35              10            25       71.428571
0         Emergency          40              12            28       70.000000
2       Orthopedics          30               9            21       70.000000
7        Gynecology          30              10            20       66.666667
5  General Medicine          50              18            32       64.000000
4        Pediatrics          30              11            19       63.333333
6       Dermatology          20               8            12       60.000000

In [178]:
departments_clean["staff_per_bed"] = (departments_clean["staff_count"]/departments_clean["total_beds"])
print(departments_clean[["department_name","total_beds","staff_count","staff_per_bed"]].sort_values("staff_per_bed",ascending = False))

    department_name  total_beds  staff_count  staff_per_bed
6       Dermatology          20           24       1.200000
4        Pediatrics          30           35       1.166667
3         Neurology          25           29       1.160000
7        Gynecology          30           34       1.133333
5  General Medicine          50           55       1.100000
1        Cardiology          35           38       1.085714
2       Orthopedics          30           32       1.066667
0         Emergency          40           42       1.050000

In [179]:
print(departments_clean[["department_name","occupancy_rate","staff_per_bed"]].sort_values("occupancy_rate",ascending = False))

    department_name  occupancy_rate  staff_per_bed
3         Neurology       72.000000       1.160000
1        Cardiology       71.428571       1.085714
0         Emergency       70.000000       1.050000
2       Orthopedics       70.000000       1.066667
7        Gynecology       66.666667       1.133333
5  General Medicine       64.000000       1.100000
4        Pediatrics       63.333333       1.166667
6       Dermatology       60.000000       1.200000

In [180]:
departments_clean.to_csv("cleaned_data/departments_clean.csv",index = False)
print("Updatd departments table saved successfully!")

Updatd departments table saved successfully!

In [181]:
# EDA for Patients table

In [182]:
print("Shape:",patients_clean.shape)
print("null:",patients_clean.isnull().sum())
print("Duplicated:",patients_clean.duplicated().sum())
print("Datatypes:",patients_clean.dtypes)
patients_clean.head()

Shape: (12000, 8)
null: patient_id           0
patient_name         0
gender               0
date_of_birth        0
city                 0
state                0
registration_date    0
insurance_type       0
dtype: int64
Duplicated: 0
Datatypes: patient_id                    int64
patient_name                    str
gender                          str
date_of_birth        datetime64[us]
city                            str
state                           str
registration_date    datetime64[us]
insurance_type                  str
dtype: object

,patient_id,patient_name,gender,date_of_birth,city,state,registration_date,insurance_type
0,100001,Patient_100001,Male,1966-05-04,Trichy,Tamil Nadu,2024-09-09,Corporate
1,100002,Patient_100002,Male,2018-09-25,Mumbai,Maharashtra,2025-05-22,Private
2,100003,Patient_100003,Male,2000-08-20,Visakhapatnam,Andhra Pradesh,2024-01-06,Private
3,100004,Patient_100004,Female,2000-10-31,Kochi,Kerala,2025-03-12,Private
4,100005,Patient_100005,Female,1955-06-23,Hyderabad,Telangana,2025-04-12,Government

In [183]:
print("Gender Distribution:")
print(patients_clean["gender"].value_counts())
print(patients_clean["gender"].value_counts(normalize = True).mul(100).round(2))

Gender Distribution:
gender
Male      6119
Female    5740
Other      141
Name: count, dtype: int64
gender
Male      50.99
Female    47.83
Other      1.18
Name: proportion, dtype: float64

In [184]:
print("Insurance Distribution:")
print(patients_clean["insurance_type"].value_counts())
print(patients_clean["insurance_type"].value_counts(normalize = True).mul(100).round(2))

Insurance Distribution:
insurance_type
Private       4524
Government    3310
Self-Pay      2644
Corporate     1487
Unknown         35
Name: count, dtype: int64
insurance_type
Private       37.70
Government    27.58
Self-Pay      22.03
Corporate     12.39
Unknown        0.29
Name: proportion, dtype: float64

In [185]:
print("state Distribution:")
print(patients_clean["state"].value_counts())
print(patients_clean["state"].value_counts(normalize = True).mul(100).round(2))

state Distribution:
state
Maharashtra       1596
Tamil Nadu        1523
Delhi             1517
Telangana         1487
Kerala            1477
Karnataka         1477
Andhra Pradesh    1468
Gujarat           1455
Name: count, dtype: int64
state
Maharashtra       13.30
Tamil Nadu        12.69
Delhi             12.64
Telangana         12.39
Kerala            12.31
Karnataka         12.31
Andhra Pradesh    12.23
Gujarat           12.12
Name: proportion, dtype: float64

In [186]:
from datetime import datetime 
today = pd.Timestamp.today()
patients_clean["age"]= ((today - patients_clean["date_of_birth"]).dt.days/365.25).round(2)
print("age Statistics")
print(patients_clean["age"].describe())
print(patients_clean["age"].isnull().sum())

age Statistics
count    12000.000000
mean        41.638120
std         23.074926
min          1.710000
25%         21.840000
50%         41.335000
75%         61.802500
max         81.690000
Name: age, dtype: float64
0

In [187]:
bins = [0,18,35,50,65,100]
labels = ["0-17","18-24","35-49","50-64","65+"]
patients_clean["age_group"] = pd.cut(patients_clean["age"],bins=bins,labels=labels,right=False)
print("Age group Distribution")
print(patients_clean["age_group"].value_counts().sort_index())
print(patients_clean["age_group"].value_counts(normalize = True).mul(100).round(2))

Age group Distribution
age_group
0-17     2429
18-24    2607
35-49    2272
50-64    2188
65+      2504
Name: count, dtype: int64
age_group
18-24    21.72
65+      20.87
0-17     20.24
35-49    18.93
50-64    18.23
Name: proportion, dtype: float64

In [188]:
print("Registration year Distribution")
print(patients_clean["registration_date"].dt.year.value_counts().sort_index())
print("Registrarion month Distribution")
print(patients_clean["registration_date"].dt.month_name().value_counts())

Registration year Distribution
registration_date
2023    3402
2024    3508
2025    3402
2026    1688
Name: count, dtype: int64
Registrarion month Distribution
registration_date
January      1226
April        1189
May          1158
March        1147
June         1109
February     1038
October       923
July          858
December      854
August        853
November      833
September     812
Name: count, dtype: int64

In [189]:
print("City Distribution")
print(patients_clean["city"].value_counts().sort_index())
print(patients_clean["city"].value_counts(normalize = True).mul(100).round(2))

City Distribution
city
Ahmedabad         721
Bengaluru         733
Chennai           296
Coimbatore        298
Hyderabad         717
Kochi             705
Kozhikode         766
Madurai           293
Mumbai            803
Mysuru            735
New Delhi        1512
Pune              782
Salem             311
Surat             726
Trichy            316
Unknown            60
Vijayawada        760
Visakhapatnam     705
Warangal          761
Name: count, dtype: int64
city
New Delhi        12.60
Mumbai            6.69
Pune              6.52
Kozhikode         6.38
Warangal          6.34
Vijayawada        6.33
Mysuru            6.12
Bengaluru         6.11
Surat             6.05
Ahmedabad         6.01
Hyderabad         5.98
Visakhapatnam     5.88
Kochi             5.88
Trichy            2.63
Salem             2.59
Coimbatore        2.48
Chennai           2.47
Madurai           2.44
Unknown           0.50
Name: proportion, dtype: float64

In [190]:
# checking impossible registration Dates 
invalid_registration = patients_clean[patients_clean["registration_date"] < patients_clean["date_of_birth"]]
print(len(invalid_registration))
print(invalid_registration[["patient_id","patient_name","date_of_birth","registration_date"]].head())

88
     patient_id    patient_name date_of_birth registration_date
90       100091  Patient_100091    2023-06-21        2023-02-11
121      100122  Patient_100122    2024-04-19        2024-01-02
142      100143  Patient_100143    2024-11-17        2023-01-16
174      100175  Patient_100175    2024-11-01        2023-03-08
401      100402  Patient_100402    2024-07-06        2023-08-01

In [191]:
patients_clean["registrstion_data_valid"] = (patients_clean["registration_date"]>=patients_clean["date_of_birth"])
print(patients_clean["registrstion_data_valid"].value_counts())

registrstion_data_valid
True     11912
False       88
Name: count, dtype: int64

In [192]:
print((~patients_clean["registrstion_data_valid"]).sum())

88

In [193]:
patients_clean["age_at_registration"] = ((patients_clean["registration_date"] - patients_clean["date_of_birth"]).dt.days/365.25 ).round(2)
print(patients_clean["age_at_registration"].describe())

count    12000.000000
mean        39.691740
std         23.096695
min         -1.840000
25%         19.837500
50%         39.620000
75%         59.900000
max         81.340000
Name: age_at_registration, dtype: float64

In [194]:
print(patients_clean[patients_clean["age_at_registration"]<0][["patient_id","date_of_birth","registration_date","age_at_registration"]].head(10))

     patient_id date_of_birth registration_date  age_at_registration
90       100091    2023-06-21        2023-02-11                -0.36
121      100122    2024-04-19        2024-01-02                -0.30
142      100143    2024-11-17        2023-01-16                -1.84
174      100175    2024-11-01        2023-03-08                -1.65
401      100402    2024-07-06        2023-08-01                -0.93
417      100418    2023-08-20        2023-01-31                -0.55
434      100435    2024-09-17        2023-07-29                -1.14
638      100639    2023-04-14        2023-03-17                -0.08
651      100652    2023-11-30        2023-07-07                -0.40
899      100900    2024-12-08        2024-01-28                -0.86

In [195]:
import numpy as np
patients_clean.loc[patients_clean["age_at_registration"]<0,"age_at_registration"] = np.nan
print("mission age_at_registration:",patients_clean["age_at_registration"].isnull().sum())

mission age_at_registration: 88

In [196]:
print(patients_clean["age_at_registration"].describe())

count    11912.00000
mean        39.99058
std         22.91763
min          0.00000
25%         20.29500
50%         39.90500
75%         60.09250
max         81.34000
Name: age_at_registration, dtype: float64

In [197]:
print(patients_clean[patients_clean["age_at_registration"]>100][["patient_id","date_of_birth","registration_date","age_at_registration"]].head(10))

Empty DataFrame
Columns: [patient_id, date_of_birth, registration_date, age_at_registration]
Index: []

In [198]:
print(patients_clean["patient_id"].duplicated().sum())
print(patients_clean.duplicated().sum())
print(patients_clean.isnull().sum())

0
0
patient_id                  0
patient_name                0
gender                      0
date_of_birth               0
city                        0
state                       0
registration_date           0
insurance_type              0
age                         0
age_group                   0
registrstion_data_valid     0
age_at_registration        88
dtype: int64

In [199]:
patients_clean = patients_clean[patients_clean["registrstion_data_valid"] == True].copy()
print("Rows after removed invaild records:",len(patients_clean))

Rows after removed invaild records: 11912

In [200]:
print(patients_clean.shape)
print(patients_clean.duplicated().sum())
print(patients_clean.isnull().sum())
print(patients_clean["patient_id"].duplicated().sum())

(11912, 12)
0
patient_id                 0
patient_name               0
gender                     0
date_of_birth              0
city                       0
state                      0
registration_date          0
insurance_type             0
age                        0
age_group                  0
registrstion_data_valid    0
age_at_registration        0
dtype: int64
0

In [201]:
patients_clean.head()

,patient_id,patient_name,gender,date_of_birth,city,state,registration_date,insurance_type,age,age_group,registrstion_data_valid,age_at_registration
0,100001,Patient_100001,Male,1966-05-04,Trichy,Tamil Nadu,2024-09-09,Corporate,60.35,50-64,True,58.35
1,100002,Patient_100002,Male,2018-09-25,Mumbai,Maharashtra,2025-05-22,Private,7.96,0-17,True,6.66
2,100003,Patient_100003,Male,2000-08-20,Visakhapatnam,Andhra Pradesh,2024-01-06,Private,26.05,18-24,True,23.38
3,100004,Patient_100004,Female,2000-10-31,Kochi,Kerala,2025-03-12,Private,25.86,18-24,True,24.36
4,100005,Patient_100005,Female,1955-06-23,Hyderabad,Telangana,2025-04-12,Government,71.21,65+,True,69.80

In [202]:
print(patients_clean.shape)
print(patients_clean.columns)

(11912, 12)
Index(['patient_id', 'patient_name', 'gender', 'date_of_birth', 'city',
       'state', 'registration_date', 'insurance_type', 'age', 'age_group',
       'registrstion_data_valid', 'age_at_registration'],
      dtype='str')

In [203]:
patients_clean.to_csv("patients_clean.csv",index=False)
print("patients table saved sucessfully")

patients table saved sucessfully

In [204]:
# EDA for Doctors table

In [205]:
print(doctors_clean.shape)
print(doctors_clean.columns)
doctors_clean.head()

(80, 6)
Index(['doctor_id', 'doctor_name', 'department_id', 'specialization',
       'experience_years', 'employment_type'],
      dtype='str')

,doctor_id,doctor_name,department_id,specialization,experience_years,employment_type
0,2001,Dr_2001,102,Cardiology,8.0,Full-Time
1,2002,Dr_2002,107,Dermatology,1.0,Part-Time
2,2003,Dr_2003,103,Orthopedics,8.0,Full-Time
3,2004,Dr_2004,101,Emergency Medicine,10.0,Full-Time
4,2005,Dr_2005,106,General Medicine,21.0,Full-Time

In [206]:
print("Duplicate rows:", doctors_clean.duplicated().sum())
print("Duplicate doctor IDs:", doctors_clean["doctor_id"].duplicated().sum())
print("\nMissing values:")
print(doctors_clean.isnull().sum())
print("\nExperience statistics:")
print(doctors_clean["experience_years"].describe())

Duplicate rows: 0
Duplicate doctor IDs: 0

Missing values:
doctor_id           0
doctor_name         0
department_id       0
specialization      0
experience_years    0
employment_type     0
dtype: int64

Experience statistics:
count    80.000000
mean     11.487500
std       7.741052
min       1.000000
25%       4.750000
50%      10.000000
75%      20.000000
max      24.000000
Name: experience_years, dtype: float64

In [207]:
print(doctors_clean[doctors_clean["experience_years"]<0])
print(doctors_clean[doctors_clean["experience_years"]>50])
print(doctors_clean["experience_years"].describe())

Empty DataFrame
Columns: [doctor_id, doctor_name, department_id, specialization, experience_years, employment_type]
Index: []
Empty DataFrame
Columns: [doctor_id, doctor_name, department_id, specialization, experience_years, employment_type]
Index: []
count    80.000000
mean     11.487500
std       7.741052
min       1.000000
25%       4.750000
50%      10.000000
75%      20.000000
max      24.000000
Name: experience_years, dtype: float64

In [208]:
print(doctors_clean["department_id"].unique())
print(doctors_clean["department_id"].nunique())

[102 107 103 101 106 105 104 108]
8

In [209]:
print("Invalid department IDs:")

print(doctors_clean[~doctors_clean["department_id"].isin(departments_clean["department_id"])])

Invalid department IDs:
Empty DataFrame
Columns: [doctor_id, doctor_name, department_id, specialization, experience_years, employment_type]
Index: []

In [210]:
print("Duplicate doctor IDs:", doctors_clean["doctor_id"].duplicated().sum())
print("Duplicate rows:", doctors_clean.duplicated().sum())

Duplicate doctor IDs: 0
Duplicate rows: 0

In [211]:
print("Specialization Distribution:")
print(doctors_clean["specialization"].value_counts())

print("\nEmployment Type Distribution:")
print(doctors_clean["employment_type"].value_counts())

Specialization Distribution:
specialization
Cardiology            12
General Medicine      12
Emergency Medicine    11
Pediatrics            11
Gynecology            11
Neurology             10
Dermatology            8
Orthopedics            5
Name: count, dtype: int64

Employment Type Distribution:
employment_type
Full-Time    58
Part-Time    12
Contract     10
Name: count, dtype: int64

In [212]:
print(departments_clean.isnull().sum())
print(departments_clean.duplicated().sum())
print(departments_clean.shape)
print(departments_clean.columns)
print(departments_clean.head())

department_id      0
department_name    0
department_type    0
total_beds         0
available_beds     0
staff_count        0
occupied_bed       0
occupancy_rate     0
staff_per_bed      0
dtype: int64
0
(8, 9)
Index(['department_id', 'department_name', 'department_type', 'total_beds',
       'available_beds', 'staff_count', 'occupied_bed', 'occupancy_rate',
       'staff_per_bed'],
      dtype='str')
   department_id department_name department_type  total_beds  available_beds  \
0            101       Emergency       Emergency          40              12
1            102      Cardiology       Specialty          35              10
2            103     Orthopedics       Specialty          30               9
3            104       Neurology       Specialty          25               7
4            105      Pediatrics       Specialty          30              11

   staff_count  occupied_bed  occupancy_rate  staff_per_bed
0           42            28       70.000000       1.050000
1           38            25       71.428571       1.085714
2           32            21       70.000000       1.066667
3           29            18       72.000000       1.160000
4           35            19       63.333333       1.166667

In [213]:
departments_clean.to_csv("departments_clean.csv",index = False )
print("Departments table saved successfully")

Departments table saved successfully

In [214]:
# EDA for appointments Table

In [215]:
print(appointments_clean.shape)
print(appointments_clean.isnull().sum())
print(appointments_clean.duplicated().sum())
print(appointments_clean.dtypes)

(45000, 9)
appointment_id             0
patient_id                 0
doctor_id                  0
appointment_date           0
appointment_time           0
appointment_type           0
appointment_status         0
waiting_time_minutes       0
satisfaction_score      9929
dtype: int64
0
appointment_id                   int64
patient_id                       int64
doctor_id                        int64
appointment_date        datetime64[us]
appointment_time                object
appointment_type                   str
appointment_status                 str
waiting_time_minutes           float64
satisfaction_score             float64
dtype: object

In [216]:
print(appointments_clean["appointment_status"].value_counts())
print(appointments_clean.groupby("appointment_status")["satisfaction_score"].agg(["count","min","max"]))

appointment_status
Completed      35071
No-Show         4048
Cancelled       3527
Rescheduled     2354
Name: count, dtype: int64
                    count  min  max
appointment_status
Cancelled               0  NaN  NaN
Completed           35071  2.0  5.0
No-Show                 0  NaN  NaN
Rescheduled             0  NaN  NaN

In [217]:
print(appointments_clean["waiting_time_minutes"].describe())
print(appointments_clean["waiting_time_minutes"].value_counts().head(10))

count    45000.000000
mean        28.753267
std         25.115296
min          0.000000
25%         10.000000
50%         24.000000
75%         42.000000
max        180.000000
Name: waiting_time_minutes, dtype: float64
waiting_time_minutes
0.0     7564
24.0     877
22.0     837
20.0     833
17.0     823
16.0     804
18.0     794
15.0     784
19.0     781
21.0     781
Name: count, dtype: int64

In [218]:
Q1 = appointments_clean["waiting_time_minutes"].quantile(0.25)
Q3 = appointments_clean["waiting_time_minutes"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = appointments_clean[
    (appointments_clean["waiting_time_minutes"] < lower_limit) |
    (appointments_clean["waiting_time_minutes"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Outliers:", len(outliers))

Q1: 10.0
Q3: 42.0
IQR: 32.0
Lower limit: -38.0
Upper limit: 90.0
Outliers: 1139

In [219]:
print(appointments_clean[appointments_clean["waiting_time_minutes"]>90]["waiting_time_minutes"].describe())
print(appointments_clean[appointments_clean["waiting_time_minutes"]>90]["waiting_time_minutes"].value_counts().sort_index().tail(10))

count    1139.000000
mean      109.003512
std        17.622930
min        91.000000
25%        95.000000
50%       104.000000
75%       117.000000
max       180.000000
Name: waiting_time_minutes, dtype: float64
waiting_time_minutes
164.0    1
165.0    5
166.0    1
168.0    1
169.0    1
171.0    1
172.0    2
175.0    1
176.0    1
180.0    4
Name: count, dtype: int64

In [220]:
print(appointments_clean["appointment_type"].value_counts())
print(appointments_clean["appointment_type"].value_counts(normalize = True).mul(100).round(2))

appointment_type
Consultation    21589
Follow-Up       10717
Diagnostic       9048
Emergency        3646
Name: count, dtype: int64
appointment_type
Consultation    47.98
Follow-Up       23.82
Diagnostic      20.11
Emergency        8.10
Name: proportion, dtype: float64

In [221]:
waiting_by_type = (appointments_clean.groupby("appointment_type")["waiting_time_minutes"].agg(["count","mean","median","min","max"]).sort_values("mean",ascending = False))
print(waiting_by_type)

                  count       mean  median  min    max
appointment_type
Diagnostic         9048  28.849469    24.0  0.0  180.0
Emergency          3646  28.808557    24.0  0.0  175.0
Consultation      21589  28.754736    24.0  0.0  180.0
Follow-Up         10717  28.650275    24.0  0.0  180.0

In [222]:
waiting_by_status = (appointments_clean.groupby("appointment_status")["waiting_time_minutes"].agg(["count","mean","median","min","max"]).sort_values("mean",ascending = False))
print(waiting_by_status)

                    count       mean  median  min    max
appointment_status
Rescheduled          2354  34.699660    29.0  3.0  157.0
Completed           35071  34.557041    29.0  3.0  180.0
No-Show              4048   0.035573     0.0  0.0   24.0
Cancelled            3527   0.034023     0.0  0.0   24.0

In [223]:
print(appointments_clean["satisfaction_score"].value_counts().sort_index())
print(appointments_clean["satisfaction_score"].describe())

satisfaction_score
2.0       56
3.0     1524
4.0    11267
5.0    22224
Name: count, dtype: int64
count    35071.000000
mean         4.587038
std          0.582172
min          2.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: satisfaction_score, dtype: float64

In [224]:
satisfaction_waiting = (appointments_clean.groupby("satisfaction_score")["waiting_time_minutes"].agg(["count","mean","median"]))
print(satisfaction_waiting)

                    count        mean  median
satisfaction_score
2.0                    56  108.750000   115.0
3.0                  1524   65.783465    62.0
4.0                 11267   42.253839    38.0
5.0                 22224   28.326674    25.0

In [225]:
correlation = appointments_clean[["waiting_time_minutes","satisfaction_score"]].corr()
print(correlation)

                      waiting_time_minutes  satisfaction_score
waiting_time_minutes              1.000000           -0.403102
satisfaction_score               -0.403102            1.000000

In [226]:
print(appointments_clean["appointment_date"].describe())
print(appointments_clean["appointment_date"].dt.year.value_counts().sort_index())

count                         45000
mean     2025-09-30 13:27:48.480000
min             2025-01-01 00:00:00
25%             2025-05-18 00:00:00
50%             2025-09-30 00:00:00
75%             2026-02-13 00:00:00
max             2026-06-30 00:00:00
Name: appointment_date, dtype: object
appointment_date
2025    30142
2026    14858
Name: count, dtype: int64

In [227]:
monthly_appointment = (appointments_clean.groupby(appointments_clean["appointment_date"].dt.to_period("M")).size())
print(monthly_appointment)

appointment_date
2025-01    2453
2025-02    2301
2025-03    2562
2025-04    2497
2025-05    2589
2025-06    2477
2025-07    2618
2025-08    2532
2025-09    2492
2025-10    2545
2025-11    2510
2025-12    2566
2026-01    2558
2026-02    2305
2026-03    2568
2026-04    2474
2026-05    2523
2026-06    2430
Freq: M, dtype: int64

In [228]:
status_by_type = pd.crosstab(appointments_clean["appointment_type"],appointments_clean["appointment_status"])
print(status_by_type)

appointment_status  Cancelled  Completed  No-Show  Rescheduled
appointment_type
Consultation             1710      16810     1946         1123
Diagnostic                707       7065      829          447
Emergency                 294       2810      319          223
Follow-Up                 816       8386      954          561

In [229]:
# What percentage of Emergency appointments were completed, cancelled, no-show, or rescheduled?
status_percentage = pd.crosstab(appointments_clean["appointment_type"],appointments_clean["appointment_status"],normalize=("index")).mul(100).round(2)
print(status_percentage)

appointment_status  Cancelled  Completed  No-Show  Rescheduled
appointment_type
Consultation             7.92      77.86     9.01         5.20
Diagnostic               7.81      78.08     9.16         4.94
Emergency                8.06      77.07     8.75         6.12
Follow-Up                7.61      78.25     8.90         5.23

In [230]:
# Analyze how many appointments each doctor handles and their completion rate.
# identify the top 10 doctors by appointment volume.
doctor_performance = (
    appointments_clean.groupby("doctor_id")
        .agg( total_appointments = ("appointment_id","count"),
            completed_appointments = ("appointment_status",lambda x:(x=="Completed").sum()
            )
))
doctor_performance["completion_rate"] = (doctor_performance["completed_appointments"]/doctor_performance["total_appointments"]*100).round(2)
print(doctor_performance.sort_values("total_appointments",ascending = False).head(10))
## Insight ##
# Doctor 2040 handled the most appointments: 613.
# Doctor 2029 has the highest completion rate among these 10: 80.57%.
# Doctor 2067 has the lowest: 76.39%.
# The top doctors have fairly similar completion rates, roughly 76–81%.

           total_appointments  completed_appointments  completion_rate
doctor_id
2040                      613                     476            77.65
2073                      602                     469            77.91
2029                      597                     481            80.57
2024                      595                     468            78.66
2071                      593                     455            76.73
2047                      593                     466            78.58
2067                      593                     453            76.39
2002                      592                     472            79.73
2077                      590                     454            76.95
2021                      585                     459            78.46

In [231]:
# let's look for doctors with the highest completion rate,
# while avoiding doctors who have very few appointments.
highly_completion =doctor_performance[ doctor_performance["total_appointments"]>=300].sort_values("completion_rate",ascending = False)
print(highly_completion.head(10))
## Insights ##
# Doctor 2035 has the highest completion rate among doctors with at least 300 appointments: 81.51%.

           total_appointments  completed_appointments  completion_rate
doctor_id
2035                      530                     432            81.51
2012                      582                     472            81.10
2056                      583                     470            80.62
2029                      597                     481            80.57
2061                      582                     466            80.07
2008                      547                     437            79.89
2002                      592                     472            79.73
2027                      572                     456            79.72
2053                      580                     462            79.66
2022                      580                     462            79.66

In [232]:
# let's investigate whether doctors handling more appointments also have longer waiting times.
doctor_waiting = (
    appointments_clean.groupby("doctor_id")
        .agg( total_appointments = ("appointment_id","count"),
            avg_waiting_time = ("waiting_time_minutes","mean"
            )))
doctor_waiting =doctor_waiting[doctor_waiting["total_appointments"]>=300].sort_values("avg_waiting_time",ascending = False)
print(doctor_waiting.head(10))
## Insight ##
# Doctor 2058 has the highest average waiting time amoung this group:32.12 min

           total_appointments  avg_waiting_time
doctor_id
2058                      552         32.119565
2048                      540         31.350000
2052                      542         30.728782
2012                      582         30.683849
2054                      555         30.527928
2022                      580         30.527586
2002                      592         30.444257
2035                      530         30.437736
2019                      536         30.432836
2056                      583         30.291595

In [233]:
# Workload vs waiting time correlation 
correlation = doctor_waiting[["total_appointments","avg_waiting_time"]].corr()
print(correlation)
# the correlation is -0.0183, which is essentially zero, so no linear relationship 
# so, based on data Doctor handling more appointments do not necessarily have longer waiting time

                    total_appointments  avg_waiting_time
total_appointments            1.000000         -0.018316
avg_waiting_time             -0.018316          1.000000

In [234]:
# Let's find out which doctors have the highest patient satisfaction. 
# We'll again require a minimum number of completed appointments so that a doctor with only a few ratings doesn't appear artificially high.

doctor_satisfaction = (appointments_clean[appointments_clean["satisfaction_score"]
    .notna()].groupby("doctor_id").agg(completed_appointments = ("appointment_id","count"),
                                       avg_satisfaction = ("satisfaction_score","mean")))
doctor_satisfaction = doctor_satisfaction[doctor_satisfaction["completed_appointments"]>= 100].sort_values("avg_satisfaction",ascending = False)
print(doctor_satisfaction.head(10))

           completed_appointments  avg_satisfaction
doctor_id
2028                          386          4.655440
2066                          450          4.648889
2006                          443          4.638826
2071                          455          4.632967
2069                          441          4.632653
2020                          429          4.631702
2017                          434          4.626728
2060                          425          4.625882
2009                          430          4.625581
2018                          411          4.625304

In [235]:
# Department level appointment Analysis 

appointment_department = appointments_clean.merge(
    doctors_clean[["doctor_id", "department_id"]],
    on="doctor_id",
    how="left"
)

appointment_department = appointment_department.merge(
    departments_clean[["department_id", "department_name"]],
    on="department_id",
    how="left"
)

print(appointment_department[
    ["appointment_id","doctor_id", "department_id", "department_name"]
].head())

   appointment_id  doctor_id  department_id department_name
0          300001       2002            107     Dermatology
1          300002       2010            104       Neurology
2          300003       2061            104       Neurology
3          300004       2010            104       Neurology
4          300005       2062            101       Emergency

In [236]:
## Which hospital departments handle the most appointments, 
# and how efficiently are those appointments completed?

department_appointments = (appointment_department.groupby("department_name")
    .agg(total_appointments = ("appointment_id","count"),completed_appointments = ("appointment_status",lambda x:(x=="Completed").sum())))
department_appointments["completion_rate"] =  ((department_appointments["completed_appointments"])/(department_appointments["total_appointments"])).mul(100).round(2)
department_appointments = department_appointments.sort_values("total_appointments",ascending = False)
print(department_appointments)
## Insights ## 
# General Medicine has the highest appointment valumne: 6810
# Emergency has the highest completion rate: 78.65%
# Dermatology has the lowest completion rate: 77.26%
# **completion rate are quite close across departments (77.26% - 78.65%),so there is not a major department level difference

                  total_appointments  completed_appointments  completion_rate
department_name
General Medicine                6810                    5353            78.60
Cardiology                      6797                    5303            78.02
Pediatrics                      6204                    4830            77.85
Gynecology                      6198                    4792            77.32
Emergency                       6183                    4863            78.65
Neurology                       5566                    4320            77.61
Dermatology                     4476                    3458            77.26
Orthopedics                     2766                    2152            77.80

In [237]:
# which departments have the highest patients waiting times 
department_waiting = (appointment_department.groupby("department_name")["waiting_time_minutes"]
    .agg(["count","mean","median","min","max"]).sort_values("mean",ascending = False))
print(department_waiting)
## Insight ##
# Emergency has the highest average waiting time (29.13 min), while gynecology has the lowest(28.20 min)

                  count       mean  median  min    max
department_name
Emergency          6183  29.130034    24.0  0.0  180.0
Cardiology         6797  29.025011    24.0  0.0  180.0
Pediatrics         6204  28.872179    24.0  0.0  180.0
Orthopedics        2766  28.836226    24.0  0.0  176.0
General Medicine   6810  28.765345    24.0  0.0  180.0
Neurology          5566  28.605821    24.0  0.0  164.0
Dermatology        4476  28.531278    24.0  0.0  171.0
Gynecology         6198  28.202807    24.0  0.0  161.0

In [238]:
# Department vs Patient Satisfaction.
department_satisfaction = (appointment_department[appointment_department["satisfaction_score"].notna()]
    .groupby("department_name").agg(rated_appointments = ("satisfaction_score","count"),
                                    avg_satisfaction = ("satisfaction_score","mean")).sort_values("avg_satisfaction",ascending = False))
print(department_satisfaction)
## Insights ##
# Orthopedics has the highest average satisfaction: 4.61/5.
# Pediatrics has the lowest: 4.57/5.
# The difference is only about 0.04 points, so satisfaction is very similar across departments.
# This suggests department alone doesn't explain much variation in satisfaction.

                  rated_appointments  avg_satisfaction
department_name
Orthopedics                     2152          4.609201
General Medicine                5353          4.600037
Dermatology                     3458          4.593696
Cardiology                      5303          4.589855
Neurology                       4320          4.588426
Gynecology                      4792          4.578255
Emergency                       4863          4.576804
Pediatrics                      4830          4.572671

In [239]:
## Appointments EDA — Major analyses completed
# We've now covered:
# Appointment status 
# Appointment type 
# Waiting-time statistics 
# Waiting-time outliers 
# Satisfaction distribution 
# Waiting time vs satisfaction 
# Correlation (-0.403) 
# Monthly appointment trend 
# Appointment type vs status 
# Doctor workload/performance 
# Doctor waiting time 
# Doctor workload vs waiting time (-0.018) 
# Department appointment volume 
# Department waiting time 
# Department satisfaction

In [240]:
print(admissions_clean.shape)
print(admissions_clean.duplicated().sum())
print(admissions_clean.isnull().sum())
print(admissions_clean.dtypes)

(9000, 11)
0
admission_id        0
patient_id          0
doctor_id           0
department_id       0
admission_date      0
discharge_date      0
admission_type      0
bed_number          0
admission_status    0
readmission_flag    0
length_of_stay      0
dtype: int64
admission_id                 int64
patient_id                   int64
doctor_id                    int64
department_id                int64
admission_date      datetime64[us]
discharge_date      datetime64[us]
admission_type                 str
bed_number                     str
admission_status               str
readmission_flag              bool
length_of_stay               int64
dtype: object

In [241]:
# Admissions EDA 
print("Admission Distribution:")
print(admissions_clean["admission_type"].value_counts())
print(admissions_clean["admission_type"].value_counts(normalize = True).mul(100).round(2))
## Insights ##
# Elective admissions are the largest category, accounting for 55.33% of all admissions.
# Emergency admissions account for 29.70%.
# Referral admissions account for 14.97%.
# More than half of the hospital admissions are planned/elective.

Admission Distribution:
admission_type
Elective     4980
Emergency    2673
Referral     1347
Name: count, dtype: int64
admission_type
Elective     55.33
Emergency    29.70
Referral     14.97
Name: proportion, dtype: float64

In [242]:
# Admission Status
print("Admission Status")
print(admissions_clean["admission_status"].value_counts())
print(admissions_clean["admission_status"].value_counts(normalize = True).mul(100).round(2))
## insights ## 
# 86.18% of admissions resulted in discharge.
# 8.08% of patients were transferred.
# 5.74% were still under treatment.
# The majority of admissions have a completed outcome (Discharged).

Admission Status
admission_status
Discharged         7756
Transferred         727
Under Treatment     517
Name: count, dtype: int64
admission_status
Discharged         86.18
Transferred         8.08
Under Treatment     5.74
Name: proportion, dtype: float64

In [243]:
print(admissions_clean["length_of_stay"].describe())
print(admissions_clean["length_of_stay"].value_counts().sort_index().head(20))
## Insight ## 
# The average stay is 4.01 days.
# The median is 3 days, meaning half of the patients stayed 3 days or less.
# 1-day stays are the most common: 1,561 admissions.
# 2-day stays are the second most common: 1,609 admissions.
# Most admissions are relatively short; only a small number extend beyond 10 days.
# The maximum stay is 25 days, which may be worth investigating as a potential long-stay/outlier group.

count    9000.000000
mean        4.013889
std         2.828256
min         1.000000
25%         2.000000
50%         3.000000
75%         5.000000
max        25.000000
Name: length_of_stay, dtype: float64
length_of_stay
1     1561
2     1609
3     1562
4     1198
5      978
6      652
7      499
8      262
9      237
10     139
11     103
12      64
13      48
14      28
15      17
16      13
17       4
18       9
19       8
20       5
Name: count, dtype: int64

In [244]:
## checking the outlier 
Q1 = admissions_clean["length_of_stay"].quantile(0.25)
Q3 = admissions_clean["length_of_stay"].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR
outliers = admissions_clean[
    (admissions_clean["length_of_stay"] < lower_limit) |
    (admissions_clean["length_of_stay"] > upper_limit)]
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)
print("Outliers:", len(outliers))

Q1: 2.0
Q3: 5.0
IQR: 3.0
Lower limit: -2.5
Upper limit: 9.5
Outliers: 442

In [245]:
long_stay = admissions_clean[admissions_clean["length_of_stay"]>9.5]
print(long_stay["length_of_stay"].describe())

print(long_stay["length_of_stay"].value_counts().sort_index())
# long stay admission are 442 admission with a stay of 10+ days

count    442.000000
mean      12.090498
std        2.525328
min       10.000000
25%       10.000000
50%       11.000000
75%       13.000000
max       25.000000
Name: length_of_stay, dtype: float64
length_of_stay
10    139
11    103
12     64
13     48
14     28
15     17
16     13
17      4
18      9
19      8
20      5
21      2
25      2
Name: count, dtype: int64

In [246]:
print("Readmission flags")
print(admissions_clean["readmission_flag"].value_counts())
print(admissions_clean["readmission_flag"].value_counts(normalize = True).mul(100).round(2))
## Insight ##
# The hospital readmission rate is 9.16%

Readmission flags
readmission_flag
False    8176
True      824
Name: count, dtype: int64
readmission_flag
False    90.84
True      9.16
Name: proportion, dtype: float64

In [247]:
readmission_by_type = (admissions_clean.groupby("admission_type")
    .agg(total_admission = ("admission_id","count"), readmission = ("readmission_flag","sum")))
readmission_by_type["readmission_rate"] =( readmission_by_type["readmission"] / readmission_by_type["total_admission"] * 100 ).round(2)
print(readmission_by_type.sort_values("readmission_rate",ascending = False))
## Insight ##
# Referral has the highest readmission rate: 9.35%.
# Emergency has the lowest: 8.94%.
# The difference is only 0.41 percentage points, so admission type does not appear to create a large difference in readmission rates in this dataset.
# Overall readmission rate is 9.16%.

                total_admission  readmission  readmission_rate
admission_type
Referral                   1347          126              9.35
Elective                   4980          459              9.22
Emergency                  2673          239              8.94

In [248]:
# Do readmitted patients have a difference average hospital stay compared with non-readmitted patients?
readmission_los = (admissions_clean.groupby("readmission_flag")
    .agg( admissions =("admission_id","count"), avg_length_of_stay = ("length_of_stay","mean"),medium_length_of_stay = ("length_of_stay","median")))
print(readmission_los)
## Insights ##
# non-readmitted : 4.0 days 
# readmitted : 4.08 days, That only about 0.07 days difference 
# readmitted patients have only a slightly longer average stay, and the mediun stay is identical at 3 days

                  admissions  avg_length_of_stay  medium_length_of_stay
readmission_flag
False                   8176            4.007339                    3.0
True                     824            4.078883                    3.0

In [249]:
# admission , Readmission rate 
admission_type_los = (admissions_clean.groupby("admission_type")
    .agg(admission = ("admission_id","count"),avg_length_of_stay = ("length_of_stay","mean"),medium_length_of_stay = ("length_of_stay","median"))
    .sort_values("avg_length_of_stay",ascending = False))
print(admission_type_los)
## Insights ## 
# Emergency admissions have the highest average stay: 4.08 days.
# Elective admissions have the lowest: 3.98 days.
# The difference is only about 0.10 days (~2.4 hours).
# All three groups have the same median stay of 3 days.

                admission  avg_length_of_stay  medium_length_of_stay
admission_type
Emergency            2673            4.080808                    3.0
Referral             1347            4.015590                    3.0
Elective             4980            3.977510                    3.0

In [250]:
print("unique_beds:",admissions_clean["bed_number"].nunique())
print("unique_beds:",admissions_clean["bed_number"].value_counts().head(10))

unique_beds: 400
unique_beds: bed_number
101-47    40
108-35    39
101-20    38
102-10    37
105-46    37
105-09    36
104-27    36
106-03    36
106-05    36
108-22    35
Name: count, dtype: int64

In [251]:
# Which departments handled the most admissions?
admission_departments = admissions_clean.merge(departments_clean[["department_id","department_name","total_beds"]],on = "department_id", how = "left")
department_admission = (admission_departments.groupby("department_name")
    .agg(total_admissions = ("admission_id","count"),total_beds = ("total_beds","first")).sort_values("total_admissions",ascending = False))
print(department_admission)
## Insights ##
# General Medicine has the highest number of admissions: 1,374.
# Orthopedics has the lowest: 534.
# Cardiology has 1,313 admissions with only 35 beds, which is worth investigating from a resource-utilization perspective.
# Orthopedics has 30 beds but only 534 admissions, so its bed utilization pattern may differ from other departments.

                  total_admissions  total_beds
department_name
General Medicine              1374          50
Cardiology                    1313          35
Pediatrics                    1296          30
Emergency                     1259          40
Gynecology                    1221          30
Neurology                     1082          25
Dermatology                    921          20
Orthopedics                    534          30

In [252]:
# Estimated bed days by departments 
department_bed_days = (admission_departments.groupby("department_name")
    .agg(total_admissions=("admission_id","count"),totals_beds_days = ("length_of_stay","sum"),total_beds =("total_beds","first")
        )
                      )
department_bed_days["avg_length_of_stay"] = (department_bed_days["totals_beds_days"]/ department_bed_days["total_admissions"]).round(2)
print(department_bed_days.sort_values("totals_beds_days",ascending = False))
## Insights ##
# General Medicine has the highest total bed-days: 5,469.
# Dermatology has the highest average length of stay: 4.15 days.
# Cardiology has 5,369 bed-days with only 35 beds, which suggests substantial bed usage.
# Orthopedics has the lowest bed-days: 2,156.

                  total_admissions  totals_beds_days  total_beds  \
department_name
General Medicine              1374              5469          50
Cardiology                    1313              5369          35
Pediatrics                    1296              5275          30
Emergency                     1259              5052          40
Gynecology                    1221              4764          30
Neurology                     1082              4217          25
Dermatology                    921              3823          20
Orthopedics                    534              2156          30

                  avg_length_of_stay
department_name
General Medicine                3.98
Cardiology                      4.09
Pediatrics                      4.07
Emergency                       4.01
Gynecology                      3.90
Neurology                       3.90
Dermatology                     4.15
Orthopedics                     4.04

In [253]:
## Calcualte bed untilization rate

In [254]:
print(admissions_clean["admission_date"].min())
print(admissions_clean["admission_date"].max())

2025-01-01 00:00:00
2026-06-20 00:00:00

In [255]:
analysis_days = (admissions_clean["admission_date"].max()-admissions_clean["admission_date"].min()).days+1
print("Analysis period(days)",analysis_days)

Analysis period(days) 536

In [256]:
department_bed_days["bed_utilization_rate"] = (department_bed_days["totals_beds_days"]/(department_bed_days["total_beds"]*analysis_days)*100).round(2)
print(department_bed_days[["total_admissions","totals_beds_days","total_beds","avg_length_of_stay","bed_utilization_rate"]].sort_values("bed_utilization_rate",ascending = False))
## Insight ##
# Dermatology has the highest estimated bed utilization (35.66%), while Orthopedics has the lowest (13.41%). 
# This suggests Orthopedics has considerably more unused bed capacity during the analysis period.

                  total_admissions  totals_beds_days  total_beds  \
department_name
Dermatology                    921              3823          20
Pediatrics                    1296              5275          30
Neurology                     1082              4217          25
Gynecology                    1221              4764          30
Cardiology                    1313              5369          35
Emergency                     1259              5052          40
General Medicine              1374              5469          50
Orthopedics                    534              2156          30

                  avg_length_of_stay  bed_utilization_rate
department_name
Dermatology                     4.15                 35.66
Pediatrics                      4.07                 32.80
Neurology                       3.90                 31.47
Gynecology                      3.90                 29.63
Cardiology                      4.09                 28.62
Emergency                       4.01                 23.56
General Medicine                3.98                 20.41
Orthopedics                     4.04                 13.41

In [257]:
# EDA treatments table

In [258]:
print(treatments_clean.shape)
print(treatments_clean.isnull().sum())
print(treatments_clean.duplicated().sum())
print(treatments_clean.dtypes)

(12892, 8)
treatment_id                  0
admission_id                  0
treatment_date                0
diagnosis                     0
treatment_type                0
treatment_cost                0
treatment_duration_minutes    0
treatment_outcome             0
dtype: int64
0
treatment_id                           int64
admission_id                           int64
treatment_date                datetime64[us]
diagnosis                                str
treatment_type                           str
treatment_cost                       float64
treatment_duration_minutes             int64
treatment_outcome                        str
dtype: object

In [259]:
treatments_clean.head()

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved
1,500002,404182,2026-03-14,Pregnancy-related,Surgery,3860.45,78,Improved
2,500003,407778,2025-02-01,Asthma,Diagnostic Test,500.19,68,Improved
3,500004,404983,2025-11-07,Pregnancy-related,Consultation,3070.55,94,Referred
4,500005,400587,2025-11-23,Migraine,Surgery,1265.82,51,Improved

In [260]:
print(treatments_clean["treatment_type"].value_counts())

treatment_type
Medication         3938
Diagnostic Test    2521
Procedure          2108
Therapy            1517
Consultation       1498
Surgery            1310
Name: count, dtype: int64

In [261]:
print(treatments_clean["treatment_type"].value_counts(normalize = True).mul(100).round(2))

treatment_type
Medication         30.55
Diagnostic Test    19.55
Procedure          16.35
Therapy            11.77
Consultation       11.62
Surgery            10.16
Name: proportion, dtype: float64

In [262]:
print(treatments_clean["treatment_outcome"].value_counts())

treatment_outcome
Improved        8769
Stable          2610
Referred        1029
Complication     484
Name: count, dtype: int64

In [263]:
print(treatments_clean["treatment_outcome"].value_counts(normalize = True).mul(100).round(2))
## Insights ##
# 68.02% of treatments resulted in an Improved outcome.
# 20.25% resulted in a Stable condition.
# 7.98% were Referred.
# 3.75% resulted in Complications.

treatment_outcome
Improved        68.02
Stable          20.25
Referred         7.98
Complication     3.75
Name: proportion, dtype: float64

In [264]:
print(treatments_clean["treatment_cost"].describe())

count    12892.000000
mean      3925.356212
std       3416.862045
min        250.000000
25%       1789.480000
50%       2966.620000
75%       4934.352500
max      54257.790000
Name: treatment_cost, dtype: float64

In [265]:
print(treatments_clean["treatment_duration_minutes"].describe())

count    12892.000000
mean        76.842460
std         52.493976
min         10.000000
25%         38.000000
50%         65.000000
75%        103.000000
max        360.000000
Name: treatment_duration_minutes, dtype: float64

In [266]:
# treatment type VS cost and duration analysis 
treatment_type_analysis = (treatments_clean
    .groupby("treatment_type")
    .agg(treatment_count = ("treatment_id","count"),avg_cost =("treatment_cost","mean"),
         median_cost =("treatment_cost","median"),avg_duration =("treatment_duration_minutes","mean"),
         median_duration =("treatment_duration_minutes","mean"))).round(2)
treatment_type_analysis = treatment_type_analysis.sort_values("avg_cost",ascending = False)
treatment_type_analysis
## insights ##
# Highest average cost: Medication — ₹3,970.72
# Lowest average cost: Consultation — ₹3,857.24
# Longest average duration: Medication — 77.91 minutes
# Shortest average duration: Diagnostic Test — 75.69 minutes
# The differences are actually quite small, so treatment type does not appear to strongly determine cost or duration in this dataset.

,treatment_count,avg_cost,median_cost,avg_duration,median_duration
treatment_type,,,,,
Medication,3938,3970.72,2928.36,77.91,77.91
Surgery,1310,3939.28,2967.29,76.55,76.55
Therapy,1517,3933.22,3036.14,76.86,76.86
Diagnostic Test,2521,3921.61,2980.20,75.69,75.69
Procedure,2108,3879.20,2899.54,75.76,75.76
Consultation,1498,3857.24,2966.32,77.73,77.73

In [267]:
treatments_clean["diagnosis"].value_counts()

diagnosis
Infection            1358
Cardiac Issue        1329
Skin Condition       1304
Asthma               1300
Pregnancy-related    1290
Other                1288
Diabetes             1269
Migraine             1255
Hypertension         1255
Fracture             1244
Name: count, dtype: int64

In [268]:
treatments_clean["diagnosis"].value_counts(normalize = True).mul(100).round(2)

diagnosis
Infection            10.53
Cardiac Issue        10.31
Skin Condition       10.11
Asthma               10.08
Pregnancy-related    10.01
Other                 9.99
Diabetes              9.84
Migraine              9.73
Hypertension          9.73
Fracture              9.65
Name: proportion, dtype: float64

In [269]:
# Diagnosis vs Treatment outcome analysis
diagnosis_outcome = pd.crosstab(treatments_clean["diagnosis"],treatments_clean["treatment_outcome"],normalize = "index").mul(100).round(2)
diagnosis_outcome
# Asthma has the highest improvement rate: 69.92%.
# Other has the lowest improvement rate: 65.14%.
# Fracture has the highest complication rate: 4.82%.
# Diabetes has the lowest complication rate: 2.92%.
# Other has the highest referral rate: 10.02%.
# Overall, the differences are relatively small, but they can still be useful for identifying areas that deserve further investigation.

treatment_outcome  Complication  Improved  Referred  Stable
diagnosis
Asthma                     3.77     69.92      7.69   18.62
Cardiac Issue              3.69     68.55      7.00   20.77
Diabetes                   2.92     67.93      8.27   20.88
Fracture                   4.82     68.73      6.43   20.02
Hypertension               3.82     69.08      7.17   19.92
Infection                  4.12     68.11      7.36   20.40
Migraine                   3.98     67.57      7.97   20.48
Other                      3.49     65.14     10.02   21.35
Pregnancy-related          3.33     69.22      9.22   18.22
Skin Condition             3.60     65.95      8.67   21.78

In [270]:
diagnosis_cost = treatments_clean.groupby("diagnosis").agg(
    treatment_count=("treatment_id", "count"),
    avg_cost=("treatment_cost", "mean"),
    median_cost=("treatment_cost", "median"),
    avg_duration=("treatment_duration_minutes", "mean")
).round(2)

diagnosis_cost = diagnosis_cost.sort_values(
    "avg_cost", ascending=False
)

diagnosis_cost

                   treatment_count  avg_cost  median_cost  avg_duration
diagnosis
Migraine                      1255   4046.96      2937.58         76.45
Pregnancy-related             1290   3991.06      3049.33         76.70
Asthma                        1300   3962.43      2906.21         77.49
Other                         1288   3933.56      3001.00         76.55
Cardiac Issue                 1329   3930.14      2886.30         76.18
Infection                     1358   3927.42      2966.62         77.34
Fracture                      1244   3918.15      2917.33         78.14
Diabetes                      1269   3899.91      3032.58         73.77
Hypertension                  1255   3830.85      2966.62         78.83
Skin Condition                1304   3813.83      2945.56         77.00

In [271]:
# outlier for the treatment cost 
Q1 = treatments_clean["treatment_cost"].quantile(0.25)
Q3 = treatments_clean["treatment_cost"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

Q1: 1789.48
Q3: 4934.3525
IQR: 3144.8725
Lower Bound: -2927.82875
Upper Bound: 9651.661250000001

In [272]:
cost_outliers = treatments_clean[
    (treatments_clean["treatment_cost"] < lower_bound) |
    (treatments_clean["treatment_cost"] > upper_bound)
]

print("Number of cost outliers:", len(cost_outliers))
print("Percentage:",round(len(cost_outliers) / len(treatments_clean) * 100,2))

Number of cost outliers: 728
Percentage: 5.65

In [273]:
# Analysis cost Outlier 
cost_outlier_analysis = (cost_outliers.groupby("treatment_type")
    .agg(outlier_count = ("treatment_id","count"),avg_cost = ("treatment_cost","mean"),max_cost = ("treatment_cost","max")).round(2))
cost_outlier_analysis = cost_outlier_analysis.sort_values("outlier_count",ascending = False )
cost_outlier_analysis
# Medication has the largest number of outlier(246), but that's partly because medication is also the most common treatment type.
# procedure has the highest average cost among the outliers: 14,555.53

                 outlier_count  avg_cost  max_cost
treatment_type
Medication                 246  14038.79  54257.79
Diagnostic Test            140  13669.63  41763.55
Procedure                  110  14555.53  52545.49
Consultation                79  13519.88  31178.90
Surgery                     79  13918.24  40590.53
Therapy                     74  14478.78  36665.74

In [274]:
# what percentage of each treatment type is ususually expensive?
outlier_rate = (cost_outliers["treatment_type"].value_counts()
    .div(treatments_clean["treatment_type"].value_counts()).mul(100).round(2).sort_values(ascending = False))
outlier_rate

treatment_type
Medication         6.25
Surgery            6.03
Diagnostic Test    5.55
Consultation       5.27
Procedure          5.22
Therapy            4.88
Name: count, dtype: float64

In [275]:
# outlier for treatment_duration_minutes
Q1_duration = treatments_clean["treatment_duration_minutes"].quantile(0.25)
Q3_duration = treatments_clean["treatment_duration_minutes"].quantile(0.75)

IQR_duration = Q3_duration - Q1_duration

lower_duration = Q1_duration - 1.5 * IQR_duration
upper_duration = Q3_duration + 1.5 * IQR_duration

print("Q1:", Q1_duration)
print("Q3:", Q3_duration)
print("IQR:", IQR_duration)
print("Lower Bound:", lower_duration)
print("Upper Bound:", upper_duration)

Q1: 38.0
Q3: 103.0
IQR: 65.0
Lower Bound: -59.5
Upper Bound: 200.5

In [276]:
duration_outliers = treatments_clean[
    (treatments_clean["treatment_duration_minutes"] < lower_duration) |
    (treatments_clean["treatment_duration_minutes"] > upper_duration)
]

print("Number of duration outliers:", len(duration_outliers))
print(
    "Percentage:",
    round(len(duration_outliers) / len(treatments_clean) * 100, 2)
)

Number of duration outliers: 393
Percentage: 3.05

In [277]:
duration_outlier_analysis = (duration_outliers.groupby("treatment_type")
    .agg(outlier_count = ("treatment_id","count"),
         avg_duration = ("treatment_duration_minutes","mean"),max_duration = ("treatment_duration_minutes","max")).round(2))
duration_outlier_analysis = duration_outlier_analysis.sort_values("outlier_count",ascending = False)
duration_outlier_analysis
## Insight ##
# Medication has the highest number of long-duration outliers: 137.
# Diagnostic Tests have the highest average duration among the outliers: 251.88 minutes (~4.2 hours).
# Several treatment types reach 360 minutes (6 hours).
# These should not automatically be removed because long treatments may be legitimate.

                 outlier_count  avg_duration  max_duration
treatment_type
Medication                 137        243.35           360
Diagnostic Test             74        251.88           360
Procedure                   52        247.23           360
Consultation                47        235.91           330
Surgery                     43        248.86           360
Therapy                     40        234.32           341

In [278]:
## Do longer treatments tend to cost more??
cost_duration_corr = treatments_clean[
    ["treatment_cost", "treatment_duration_minutes"]
].corr()

cost_duration_corr

                            treatment_cost  treatment_duration_minutes
treatment_cost                    1.000000                   -0.004097
treatment_duration_minutes       -0.004097                    1.000000

In [279]:
correlation = treatments_clean["treatment_cost"].corr(
    treatments_clean["treatment_duration_minutes"]
)

print("Cost vs Duration Correlation:", round(correlation, 3))
# Extremely close to 0, a longer treatment does not necessarily mean a more expensive treatment here

Cost vs Duration Correlation: -0.004

In [280]:
treatments_clean

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved
1,500002,404182,2026-03-14,Pregnancy-related,Surgery,3860.45,78,Improved
2,500003,407778,2025-02-01,Asthma,Diagnostic Test,500.19,68,Improved
3,500004,404983,2025-11-07,Pregnancy-related,Consultation,3070.55,94,Referred
4,500005,400587,2025-11-23,Migraine,Surgery,1265.82,51,Improved
...,...,...,...,...,...,...,...,...
17994,517995,405999,2025-05-01,Cardiac Issue,Therapy,1831.92,65,Referred
17995,517996,406383,2026-03-15,Asthma,Therapy,1389.76,76,Improved
17997,517998,402889,2025-01-18,Fracture,Surgery,10044.36,52,Complication
17998,517999,408605,2025-03-28,Other,Consultation,724.63,70,Stable
17999,518000,403423,2025-04-21,Fracture,Surgery,7817.90,66,Improved

In [281]:
# Do treatments with different outcomes have different average costs?
outcome_cost_analysis = treatments_clean.groupby("treatment_outcome").agg(
    treatment_count=("treatment_id", "count"),
    avg_cost=("treatment_cost", "mean"),
    median_cost=("treatment_cost", "median"),
    avg_duration=("treatment_duration_minutes", "mean")
).round(2)

outcome_cost_analysis = outcome_cost_analysis.sort_values(
    "avg_cost", ascending=False
)
outcome_cost_analysis
## Insight ##
# Improved treatments have the highest average cost: ₹3,950.31.
# Complication cases have the lowest average cost: ₹3,831.69.
# The cost difference is relatively small.
# Complication cases also have the lowest average duration (72.78 minutes).

                   treatment_count  avg_cost  median_cost  avg_duration
treatment_outcome
Improved                      8769   3950.31      2966.62         77.36
Referred                      1029   3924.21      2972.74         76.00
Stable                        2610   3859.32      2902.40         76.20
Complication                   484   3831.69      2823.90         72.78

In [282]:
# Which hospital departments handle the most treatments, and what are their treatment costs and outcomes?
# First, merge treatments table with admissions
treatment_admission = (treatments_clean.merge(admissions_clean[["admission_id","department_id","admission_type"]], on = "admission_id", how = "left"))
treatment_admission.head()

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome,department_id,admission_type
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved,102,Elective
1,500002,404182,2026-03-14,Pregnancy-related,Surgery,3860.45,78,Improved,105,Emergency
2,500003,407778,2025-02-01,Asthma,Diagnostic Test,500.19,68,Improved,105,Elective
3,500004,404983,2025-11-07,Pregnancy-related,Consultation,3070.55,94,Referred,105,Elective
4,500005,400587,2025-11-23,Migraine,Surgery,1265.82,51,Improved,106,Referral

In [283]:
print(treatment_admission.shape)
print(treatment_admission["department_id"].isna().sum())

(12892, 10)
0

In [284]:
print(treatment_admission.columns)

Index(['treatment_id', 'admission_id', 'treatment_date', 'diagnosis',
       'treatment_type', 'treatment_cost', 'treatment_duration_minutes',
       'treatment_outcome', 'department_id', 'admission_type'],
      dtype='str')

In [285]:
treatment_admission.columns.tolist()

['treatment_id',
 'admission_id',
 'treatment_date',
 'diagnosis',
 'treatment_type',
 'treatment_cost',
 'treatment_duration_minutes',
 'treatment_outcome',
 'department_id',
 'admission_type']

In [286]:
departments_clean.columns.tolist()

['department_id',
 'department_name',
 'department_type',
 'total_beds',
 'available_beds',
 'staff_count',
 'occupied_bed',
 'occupancy_rate',
 'staff_per_bed']

In [287]:
departments_clean.columns.duplicated().sum()

np.int64(0)

In [288]:
treatment_department = treatment_admission.merge(
    departments_clean[["department_id", "department_name"]],
    on="department_id",
    how="left"
)

print("Shape:", treatment_department.shape)
print("Missing Department Names:",
      treatment_department["department_name"].isna().sum())

Shape: (12892, 11)
Missing Department Names: 0

In [289]:
treatment_department.head()

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome,department_id,admission_type,department_name
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved,102,Elective,Cardiology
1,500002,404182,2026-03-14,Pregnancy-related,Surgery,3860.45,78,Improved,105,Emergency,Pediatrics
2,500003,407778,2025-02-01,Asthma,Diagnostic Test,500.19,68,Improved,105,Elective,Pediatrics
3,500004,404983,2025-11-07,Pregnancy-related,Consultation,3070.55,94,Referred,105,Elective,Pediatrics
4,500005,400587,2025-11-23,Migraine,Surgery,1265.82,51,Improved,106,Referral,General Medicine

In [290]:
# which departments handling the most treatments, and what are thier average treatments costs and durations?
department_treatment_analysis = treatment_department.groupby("department_name").agg(trearment_count = ("treatment_id","count"),avg_cost = ("treatment_cost","mean")
         ,median_cost = ("treatment_cost","median"),avg_duration = ("treatment_duration_minutes","mean")).round(2)
department_treatment_analysis = department_treatment_analysis.sort_values("trearment_count",ascending = False)
department_treatment_analysis
# General Medicine handles the most treatments: 1,968.
# Cardiology has the highest average cost: ₹4,000.77.
# Gynecology has the longest average treatment duration: 78.48 minutes.
# Orthopedics has the shortest: 75.28 minutes.
# Neurology has the lowest average cost: ₹3,756.84.

                  trearment_count  avg_cost  median_cost  avg_duration
department_name
General Medicine             1968   3984.60      3012.76         76.16
Cardiology                   1900   4000.77      3041.62         76.06
Pediatrics                   1885   3890.31      2954.66         77.05
Emergency                    1818   3982.33      2951.88         77.87
Gynecology                   1731   3954.92      3035.07         78.48
Neurology                    1558   3756.84      2887.47         75.90
Dermatology                  1274   3840.09      2831.12         77.14
Orthopedics                   758   3955.17      2873.57         75.28

In [291]:
# which departments have the highest imporvements and complicated rates?
department_outcome = pd.crosstab(treatment_department["department_name"],treatment_department["treatment_outcome"],normalize = "index").mul(100).round(2)
department_outcome
# Cardiology has the highest Improved rate: 70.21%.
# Pediatrics has the highest Complication rate: 4.83%.
# Orthopedics has the lowest complication rate: 2.64%.
# Neurology has the highest Stable rate: 22.59%.
# Orthopedics has the highest Referred rate: 8.71%.
# Overall, improvement is the dominant outcome in every department.

treatment_outcome  Complication  Improved  Referred  Stable
department_name
Cardiology                 4.00     70.21      7.68   18.11
Dermatology                3.77     68.60      8.56   19.07
Emergency                  3.25     68.43      8.64   19.69
General Medicine           3.61     67.28      8.38   20.73
Gynecology                 3.64     68.34      7.80   20.22
Neurology                  3.59     65.85      7.96   22.59
Orthopedics                2.64     66.09      8.71   22.56
Pediatrics                 4.83     68.06      6.74   20.37

In [292]:
# Does the type of admission(Elective,emergency,Referral) have different treatments outcomes?
admission_outcome = pd.crosstab(treatment_department["admission_type"],treatment_department["treatment_outcome"], normalize = "index").mul(100).round(2) 
admission_outcome
## Insight ##
# Elective admissions have the highest improvements rate:68.13%
# Referral admissions have the highest complication rate: 4.16%
# Emergency admission have the highest referred outcome:8.20%
# The difference are fairly small, so admission type doesn't appear to create a dramatic difference in treatments outcomes in this dataset.

treatment_outcome  Complication  Improved  Referred  Stable
admission_type
Elective                   3.61     68.13      7.88   20.38
Emergency                  3.82     67.96      8.20   20.03
Referral                   4.16     67.73      7.95   20.16

In [293]:
# counts 
admission_outcome = pd.crosstab(treatment_department["admission_type"],treatment_department["treatment_outcome"])
admission_outcome
## Insights ##
# Elective: 7,198 treaments 
# Emergency: 3,745
# Referral : 1,949

treatment_outcome  Complication  Improved  Referred  Stable
admission_type
Elective                    260      4904       567    1467
Emergency                   143      2545       307     750
Referral                     81      1320       155     393

In [294]:
# Treatments cost by Admission type 
# Which admission type has the highest average treatments cost and treatments duration?
admission_cost = (treatment_department.groupby("admission_type")
    .agg(treament_count = ("treatment_id","count"),avg_cost = ("treatment_cost","mean"),
         median_cost = ("treatment_cost","median"),avg_duration = ("treatment_duration_minutes","mean"))).round(2)
admission_cost = admission_cost.sort_values("avg_cost", ascending = False)
admission_cost
## Insights ## 
# Elective treatments have the highest average cost: ₹3,937.81.
# Elective treatments also have the longest average duration: 77.09 minutes.
# Referral treatments have the lowest average cost and duration.
# Again, the differences are relatively small.

                treament_count  avg_cost  median_cost  avg_duration
admission_type
Elective                  7198   3937.81      2966.62         77.09
Emergency                 3745   3916.98      2997.82         76.83
Referral                  1949   3895.45      2888.08         75.94

In [295]:
# Patients level treatment analysis 
## connecting three tables Treatments-admission-Patients
### How many treatments does each patients receive and how much has been spent on their treatments??
patient_treatment = treatment_department.merge(admissions_clean[["admission_id","patient_id"]], on = "admission_id",how = "left")
print(patient_treatment.shape)
print(patient_treatment["patient_id"].isna().sum())

(12892, 12)
0

In [296]:
# how many treatments each patient received and how much was spent 
patient_treatment_summary = (patient_treatment.groupby("patient_id")
    .agg(treatment_count = ("treatment_id","count"),total_treatment_cost = ("treatment_cost","sum"),avg_treatment_cost = ("treatment_cost","mean"),
        avg_treatment_duration = ("treatment_duration_minutes","mean"))).round(2)
patient_treatment_summary = patient_treatment_summary.sort_values("treatment_count",ascending = False)
patient_treatment_summary.head(10)

,treatment_count,total_treatment_cost,avg_treatment_cost,avg_treatment_duration
patient_id,,,,
105765,13,71711.01,5516.23,70.08
100595,13,73328.24,5640.63,57.62
109045,12,58556.92,4879.74,79.50
111001,12,54115.60,4509.63,73.08
105201,12,47511.92,3959.33,70.33
109547,11,44834.87,4075.90,93.09
105275,11,37812.36,3437.49,77.00
105581,11,44200.39,4018.22,81.91
107870,11,39555.08,3595.92,84.64
101625,11,37523.15,3411.20,94.00

In [297]:
#Highest cost Patients 
# which patients generated the highest total treatments costs?
highest_cost_patient = patient_treatment_summary.sort_values("total_treatment_cost", ascending = False)
highest_cost_patient.head(10)
## Insight ## 
# Patient 110156 is particularly interesting:
# Only 3 treatments
# Total cost: ₹60,859.21
# Average cost: ₹20,286.40
# So high total cost doesn't always mean high treatment frequency.
# Patient 100595, on the other hand, has the most treatments (13) and the highest total cost.

,treatment_count,total_treatment_cost,avg_treatment_cost,avg_treatment_duration
patient_id,,,,
100595,13,73328.24,5640.63,57.62
108290,9,73297.50,8144.17,72.44
105765,13,71711.01,5516.23,70.08
105686,5,63918.14,12783.63,55.60
107534,10,63038.76,6303.88,62.50
110156,3,60859.21,20286.40,81.33
109045,12,58556.92,4879.74,79.50
103784,7,57153.38,8164.77,103.71
105644,8,54748.82,6843.60,60.75
111001,12,54115.60,4509.63,73.08

In [298]:
# Treatment Frequency vs total cost 
patients_cost_corr = patient_treatment_summary[["treatment_count","total_treatment_cost"]].corr()
patients_cost_corr

                      treatment_count  total_treatment_cost
treatment_count              1.000000              0.777359
total_treatment_cost         0.777359              1.000000

In [299]:
correlation = patient_treatment_summary["treatment_count"].corr(patient_treatment_summary["total_treatment_cost"])
print(round(correlation,3))
# Correlation = 0.777
# This indicates a strong positive relationship:
# Patients who receive more treatments tend to have higher total treatment costs.

0.777

In [300]:
patient_treatment_summary["treatment_count"].describe()

count    5089.000000
mean        2.533307
std         1.710964
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max        13.000000
Name: treatment_count, dtype: float64

In [301]:
Q1_patient = patient_treatment_summary["treatment_count"].quantile(0.25)
Q3_patient = patient_treatment_summary["treatment_count"].quantile(0.75)

IQR_patient = Q3_patient - Q1_patient

upper_patient = Q3_patient + 1.5 * IQR_patient

print("Q1:", Q1_patient)
print("Q3:", Q3_patient)
print("IQR:", IQR_patient)
print("Upper Bound:", upper_patient)

Q1: 1.0
Q3: 3.0
IQR: 2.0
Upper Bound: 6.0

In [302]:
high_frequency_patients = patient_treatment_summary[
    patient_treatment_summary["treatment_count"] > upper_patient
]

print("High-frequency patients:", len(high_frequency_patients))
print(
    "Percentage:",
    round(
        len(high_frequency_patients) /
        len(patient_treatment_summary) * 100,
        2
    )
)

High-frequency patients: 175
Percentage: 3.44

In [303]:
## Python main function

In [304]:
# Python in  Pivot_table function

In [305]:
treatment_pivot = pd.pivot_table(treatment_department,
                                 values="treatment_cost",
                                 index ="department_name",
                                 columns = "treatment_outcome",
                                 aggfunc="mean"
                                ).round(2)
treatment_pivot
# Cardiology + Referred: ₹4,274.59
# Dermatology + Referred: ₹4,312.68 — highest in this table
# Emergency + Improved: ₹4,047.30
# General Medicine + Improved: ₹4,050.11
# Neurology + Complication: ₹4,306.00
# Neurology + Stable: ₹3,507.70 — relatively low

treatment_outcome  Complication  Improved  Referred   Stable
department_name
Cardiology              3851.68   3956.47   4274.59  4089.31
Dermatology             3541.58   3786.60   4312.68  3879.45
Emergency               3700.20   4047.30   4030.78  3781.80
General Medicine        3811.37   4050.11   3720.98  3908.75
Gynecology              3972.88   3951.89   3863.77  3997.09
Neurology               4306.00   3801.46   3846.82  3507.70
Orthopedics             4260.88   3909.86   4241.15  3941.80
Pediatrics              3585.18   3991.79   3295.42  3820.32

In [306]:
# python in transform function

In [307]:
department_treatment_percentage = (treatment_department
    .groupby("department_name")["treatment_id"].transform("count")/len(treatment_department)*100).round(2)
department_treatment_percentage.head(10)

0    14.74
1    14.62
2    14.62
3    14.62
4    15.27
5    14.10
6    14.74
7    14.10
8     5.88
9    13.43
Name: treatment_id, dtype: float64

In [308]:
# python in apply function

In [309]:
department_treatment_summary = (treatment_department.groupby("department_name")
    .apply(lambda x:pd.Series({"total_treatments":len(x),
                              "avg_cost":x["treatment_cost"].mean(),
                              "avg_duration":x["treatment_duration_minutes"].mean()
                              })).round(2))
department_treatment_summary

                  total_treatments  avg_cost  avg_duration
department_name
Cardiology                  1900.0   4000.77         76.06
Dermatology                 1274.0   3840.09         77.14
Emergency                   1818.0   3982.33         77.87
General Medicine            1968.0   3984.60         76.16
Gynecology                  1731.0   3954.92         78.48
Neurology                   1558.0   3756.84         75.90
Orthopedics                  758.0   3955.17         75.28
Pediatrics                  1885.0   3890.31         77.05

In [310]:
# python in melt function

In [311]:
treatment_melted = treatment_pivot.reset_index().melt(
    id_vars = "department_name",
    var_name = "treatment_outcome",
    value_name = "avg_treatment_cost"
)
treatment_melted

     department_name treatment_outcome  avg_treatment_cost
0         Cardiology      Complication             3851.68
1        Dermatology      Complication             3541.58
2          Emergency      Complication             3700.20
3   General Medicine      Complication             3811.37
4         Gynecology      Complication             3972.88
5          Neurology      Complication             4306.00
6        Orthopedics      Complication             4260.88
7         Pediatrics      Complication             3585.18
8         Cardiology          Improved             3956.47
9        Dermatology          Improved             3786.60
10         Emergency          Improved             4047.30
11  General Medicine          Improved             4050.11
12        Gynecology          Improved             3951.89
13         Neurology          Improved             3801.46
14       Orthopedics          Improved             3909.86
15        Pediatrics          Improved             3991.79
16        Cardiology          Referred             4274.59
17       Dermatology          Referred             4312.68
18         Emergency          Referred             4030.78
19  General Medicine          Referred             3720.98
20        Gynecology          Referred             3863.77
21         Neurology          Referred             3846.82
22       Orthopedics          Referred             4241.15
23        Pediatrics          Referred             3295.42
24        Cardiology            Stable             4089.31
25       Dermatology            Stable             3879.45
26         Emergency            Stable             3781.80
27  General Medicine            Stable             3908.75
28        Gynecology            Stable             3997.09
29         Neurology            Stable             3507.70
30       Orthopedics            Stable             3941.80
31        Pediatrics            Stable             3820.32

In [312]:
# python in value_counts function

In [313]:
treatment_outcome_percentage = (treatment_department["treatment_outcome"].value_counts(normalize = True).mul(100).round(2))
treatment_outcome_percentage

treatment_outcome
Improved        68.02
Stable          20.25
Referred         7.98
Complication     3.75
Name: proportion, dtype: float64

In [314]:
# python in crosstab

In [315]:
treatment_type_outcome = pd.crosstab(treatment_department["treatment_type"],treatment_department["treatment_outcome"])
treatment_type_outcome

treatment_outcome  Complication  Improved  Referred  Stable
treatment_type
Consultation                 57      1024       123     294
Diagnostic Test              77      1738       192     514
Medication                  154      2617       337     830
Procedure                    83      1424       161     440
Surgery                      52       904        96     258
Therapy                      61      1062       120     274

In [316]:
# crosstab with percentage calculation

In [317]:
treatment_type_outcome = pd.crosstab(treatment_department["treatment_type"],
                                     treatment_department["treatment_outcome"],normalize = "index")*100
treatment_type_outcome = treatment_type_outcome.round(2)
treatment_type_outcome

treatment_outcome  Complication  Improved  Referred  Stable
treatment_type
Consultation               3.81     68.36      8.21   19.63
Diagnostic Test            3.05     68.94      7.62   20.39
Medication                 3.91     66.46      8.56   21.08
Procedure                  3.94     67.55      7.64   20.87
Surgery                    3.97     69.01      7.33   19.69
Therapy                    4.02     70.01      7.91   18.06

In [318]:
# python in sort_values

In [319]:
department_cost_ranking = (treatment_department.groupby("department_name")["treatment_cost"].mean().sort_values(ascending = False).round(2))
department_cost_ranking

department_name
Cardiology          4000.77
General Medicine    3984.60
Emergency           3982.33
Orthopedics         3955.17
Gynecology          3954.92
Pediatrics          3890.31
Dermatology         3840.09
Neurology           3756.84
Name: treatment_cost, dtype: float64

In [320]:
# python in nlargest() and nsmallest()

In [321]:
top_3_department = (treatment_department.groupby("department_name")["treatment_cost"].mean().nlargest(3).round(2))
top_3_department

department_name
Cardiology          4000.77
General Medicine    3984.60
Emergency           3982.33
Name: treatment_cost, dtype: float64

In [322]:
bottom_3_department = (treatment_department.groupby("department_name")["treatment_cost"].mean().nsmallest(3).round(2))
bottom_3_department

department_name
Neurology      3756.84
Dermatology    3840.09
Pediatrics     3890.31
Name: treatment_cost, dtype: float64

In [323]:
# python in query()

In [324]:
highest_cost_treatment = treatment_department.query("treatment_cost > 10000")
highest_cost_treatment.head()

,treatment_id,admission_id,treatment_date,diagnosis,treatment_type,treatment_cost,treatment_duration_minutes,treatment_outcome,department_id,admission_type,department_name
0,500001,405865,2025-08-16,Cardiac Issue,Diagnostic Test,11415.15,75,Improved,102,Elective,Cardiology
86,500123,406254,2025-09-11,Fracture,Diagnostic Test,13285.66,209,Improved,104,Referral,Neurology
91,500130,400129,2025-08-25,Asthma,Procedure,10394.12,53,Improved,101,Elective,Emergency
127,500182,404587,2025-03-17,Cardiac Issue,Consultation,14320.24,62,Improved,102,Elective,Cardiology
129,500184,408242,2025-07-22,Cardiac Issue,Medication,14475.85,91,Improved,101,Elective,Emergency

In [325]:
highest_cost_treatment = treatment_department.query("treatment_cost > 10000" and "treatment_outcome == 'Improved'")
highest_cost_treatment[["treatment_id","treatment_cost","treatment_outcome","department_name"]].head(10)

    treatment_id  treatment_cost treatment_outcome   department_name
0         500001        11415.15          Improved        Cardiology
1         500002         3860.45          Improved        Pediatrics
2         500003          500.19          Improved        Pediatrics
4         500005         1265.82          Improved  General Medicine
5         500006         8017.15          Improved         Emergency
8         500010         6458.88          Improved       Orthopedics
9         500011         1210.09          Improved        Gynecology
10        500012         2927.51          Improved        Gynecology
11        500013         1560.46          Improved        Gynecology
12        500014         3212.68          Improved         Neurology

In [326]:
print(treatment_department["treatment_cost"].dtype)

print(
    treatment_department[
        (treatment_department["treatment_cost"] > 10000) &
        (treatment_department["treatment_outcome"] == "Improved")
    ][[
        "treatment_id",
        "treatment_cost",
        "treatment_outcome",
        "department_name"
    ]].head(10)
)

float64
     treatment_id  treatment_cost treatment_outcome   department_name
0          500001        11415.15          Improved        Cardiology
86         500123        13285.66          Improved         Neurology
91         500130        10394.12          Improved         Emergency
127        500182        14320.24          Improved        Cardiology
129        500184        14475.85          Improved         Emergency
132        500187        12768.41          Improved         Emergency
161        500229        22516.98          Improved        Pediatrics
162        500230        10710.71          Improved  General Medicine
167        500238        10041.89          Improved        Pediatrics
211        500301        10442.34          Improved        Pediatrics

In [327]:
# python in loc[] and iloc[]

In [328]:
highest_cost_treatment.loc[:,["treatment_id","treatment_cost","treatment_type","department_name"]].head(10)

    treatment_id  treatment_cost   treatment_type   department_name
0         500001        11415.15  Diagnostic Test        Cardiology
1         500002         3860.45          Surgery        Pediatrics
2         500003          500.19  Diagnostic Test        Pediatrics
4         500005         1265.82          Surgery  General Medicine
5         500006         8017.15          Surgery         Emergency
8         500010         6458.88  Diagnostic Test       Orthopedics
9         500011         1210.09     Consultation        Gynecology
10        500012         2927.51          Therapy        Gynecology
11        500013         1560.46       Medication        Gynecology
12        500014         3212.68     Consultation         Neurology

In [329]:
high_cost_improved = treatment_department.loc[
    (treatment_department["treatment_cost"] > 10000) &
    (treatment_department["treatment_outcome"] == "Improved"),
    ["treatment_id", "treatment_cost", "treatment_type", "department_name"]
]

high_cost_improved.head(10)

     treatment_id  treatment_cost   treatment_type   department_name
0          500001        11415.15  Diagnostic Test        Cardiology
86         500123        13285.66  Diagnostic Test         Neurology
91         500130        10394.12        Procedure         Emergency
127        500182        14320.24     Consultation        Cardiology
129        500184        14475.85       Medication         Emergency
132        500187        12768.41     Consultation         Emergency
161        500229        22516.98       Medication        Pediatrics
162        500230        10710.71          Therapy  General Medicine
167        500238        10041.89     Consultation        Pediatrics
211        500301        10442.34          Therapy        Pediatrics

In [330]:
# By column names
#high_cost_improved.loc[:, ["treatment_id", "treatment_cost"]]

# By column positions
#high_cost_improved.iloc[:, 0:2]

In [331]:
# iloc[]
high_cost_improved.iloc[0:5,0:3]

     treatment_id  treatment_cost   treatment_type
0          500001        11415.15  Diagnostic Test
86         500123        13285.66  Diagnostic Test
91         500130        10394.12        Procedure
127        500182        14320.24     Consultation
129        500184        14475.85       Medication

In [332]:
# python in assign()

In [333]:
treatment_analysis = treatment_department.assign(treatment_cost_thousands = lambda x:x["treatment_cost"]/1000)
treatment_analysis[["treatment_id","treatment_cost","treatment_cost_thousands"]].head()

   treatment_id  treatment_cost  treatment_cost_thousands
0        500001        11415.15                  11.41515
1        500002         3860.45                   3.86045
2        500003          500.19                   0.50019
3        500004         3070.55                   3.07055
4        500005         1265.82                   1.26582

In [334]:
# python in np.where()

In [335]:
import numpy as np 
treatment_analysis = (treatment_analysis.assign(cost_category = np.where(treatment_analysis["treatment_cost"]>10000,"High Cost","Normal Cost")))
treatment_analysis[["treatment_id","treatment_cost","cost_category",]].head(10)

   treatment_id  treatment_cost cost_category
0        500001        11415.15     High Cost
1        500002         3860.45   Normal Cost
2        500003          500.19   Normal Cost
3        500004         3070.55   Normal Cost
4        500005         1265.82   Normal Cost
5        500006         8017.15   Normal Cost
6        500007         1562.90   Normal Cost
7        500008         1866.06   Normal Cost
8        500010         6458.88   Normal Cost
9        500011         1210.09   Normal Cost

In [336]:
# python in Select()

In [337]:
conditions = [treatment_analysis["treatment_cost"]<=2000,
              treatment_analysis["treatment_cost"]<=5000,
              treatment_analysis["treatment_cost"]<=10000,
              treatment_analysis["treatment_cost"]>10000]
choices = ["low","medium","High","Very high"]
treatment_analysis = treatment_analysis.assign(cost_level = np.select(conditions,choices,default = "Unknown"))
treatment_analysis[["treatment_id","treatment_cost","cost_level"]].head()

   treatment_id  treatment_cost cost_level
0        500001        11415.15  Very high
1        500002         3860.45     medium
2        500003          500.19        low
3        500004         3070.55     medium
4        500005         1265.82        low

In [338]:
# python in map()

In [339]:
outcome_map = {"Improved":"Success",
              "Stable":"Ongoing",
              "Referred":"Referral",
              "Complication":"Issue"}
treatment_analysis = treatment_analysis.assign(outcome_group = treatment_analysis["treatment_outcome"].map(outcome_map))
treatment_analysis[["treatment_id","treatment_outcome","outcome_group"]].head(10)

   treatment_id treatment_outcome outcome_group
0        500001          Improved       Success
1        500002          Improved       Success
2        500003          Improved       Success
3        500004          Referred      Referral
4        500005          Improved       Success
5        500006          Improved       Success
6        500007            Stable       Ongoing
7        500008            Stable       Ongoing
8        500010          Improved       Success
9        500011          Improved       Success

In [340]:
# python in replace

In [341]:
treatment_analysis = treatment_analysis.assign(outcome_group = treatment_analysis["treatment_outcome"].replace({"Improved":"Success",
              "Stable":"Ongoing",
              "Referred":"Referral",
              "Complication":"Issue"}))
treatment_analysis[["treatment_id","treatment_outcome","outcome_group"]].head(10)

   treatment_id treatment_outcome outcome_group
0        500001          Improved       Success
1        500002          Improved       Success
2        500003          Improved       Success
3        500004          Referred      Referral
4        500005          Improved       Success
5        500006          Improved       Success
6        500007            Stable       Ongoing
7        500008            Stable       Ongoing
8        500010          Improved       Success
9        500011          Improved       Success

In [342]:
# python in set_index() and reset_index

In [343]:
department_summary = (treatment_department.groupby("department_name")["treatment_cost"].mean().round(2))
department_summary

department_name
Cardiology          4000.77
Dermatology         3840.09
Emergency           3982.33
General Medicine    3984.60
Gynecology          3954.92
Neurology           3756.84
Orthopedics         3955.17
Pediatrics          3890.31
Name: treatment_cost, dtype: float64

In [344]:
department_summary = department_summary.reset_index()
department_summary

    department_name  treatment_cost
0        Cardiology         4000.77
1       Dermatology         3840.09
2         Emergency         3982.33
3  General Medicine         3984.60
4        Gynecology         3954.92
5         Neurology         3756.84
6       Orthopedics         3955.17
7        Pediatrics         3890.31

In [345]:
department_summary_indexed = department_summary.set_index("department_name")
department_summary_indexed

                  treatment_cost
department_name
Cardiology               4000.77
Dermatology              3840.09
Emergency                3982.33
General Medicine         3984.60
Gynecology               3954.92
Neurology                3756.84
Orthopedics              3955.17
Pediatrics               3890.31

In [346]:
# python in pd.concat()

In [347]:
part1 = department_summary.iloc[:4]
part2 = department_summary.iloc[4:]
print(part1)
print(part2)

    department_name  treatment_cost
0        Cardiology         4000.77
1       Dermatology         3840.09
2         Emergency         3982.33
3  General Medicine         3984.60
  department_name  treatment_cost
4      Gynecology         3954.92
5       Neurology         3756.84
6     Orthopedics         3955.17
7      Pediatrics         3890.31

In [348]:
combined = pd.concat([part1,part2])
combined

    department_name  treatment_cost
0        Cardiology         4000.77
1       Dermatology         3840.09
2         Emergency         3982.33
3  General Medicine         3984.60
4        Gynecology         3954.92
5         Neurology         3756.84
6       Orthopedics         3955.17
7        Pediatrics         3890.31

In [349]:
# python in rename()

In [350]:
department_summary_rename = department_summary.rename(columns ={"treatment_cost":"avg_treatment_cost"})
department_summary_rename

    department_name  avg_treatment_cost
0        Cardiology             4000.77
1       Dermatology             3840.09
2         Emergency             3982.33
3  General Medicine             3984.60
4        Gynecology             3954.92
5         Neurology             3756.84
6       Orthopedics             3955.17
7        Pediatrics             3890.31

In [351]:
# python in Drop()

In [352]:
deaprtment_summary_clean = department_summary_rename.drop(columns = ["avg_treatment_cost"])
deaprtment_summary_clean

    department_name
0        Cardiology
1       Dermatology
2         Emergency
3  General Medicine
4        Gynecology
5         Neurology
6       Orthopedics
7        Pediatrics

In [353]:
# single row drop 
department_summary_without_frist = department_summary_rename.drop(index = 0)
department_summary_without_frist

    department_name  avg_treatment_cost
1       Dermatology             3840.09
2         Emergency             3982.33
3  General Medicine             3984.60
4        Gynecology             3954.92
5         Neurology             3756.84
6       Orthopedics             3955.17
7        Pediatrics             3890.31

In [354]:
# multiple row drop 
department_summary_without_frist_two = department_summary_rename.drop(index = [0,1])
department_summary_without_frist_two

    department_name  avg_treatment_cost
2         Emergency             3982.33
3  General Medicine             3984.60
4        Gynecology             3954.92
5         Neurology             3756.84
6       Orthopedics             3955.17
7        Pediatrics             3890.31

In [355]:
# python drop() with inplace()

In [356]:
department_summary_copy = department_summary_rename.copy()
department_summary_copy.drop(index =[0,1],inplace =True)
department_summary_copy

    department_name  avg_treatment_cost
2         Emergency             3982.33
3  General Medicine             3984.60
4        Gynecology             3954.92
5         Neurology             3756.84
6       Orthopedics             3955.17
7        Pediatrics             3890.31

In [357]:
# python in Datetime . dt()

In [358]:
#year
patients_clean["registration_year"] = (
    patients_clean["registration_date"].dt.year
)

patients_clean[
    ["registration_date", "registration_year"]
].head()

  registration_date  registration_year
0        2024-09-09               2024
1        2025-05-22               2025
2        2024-01-06               2024
3        2025-03-12               2025
4        2025-04-12               2025

In [359]:
#month
patients_clean["registration_month"] = (
    patients_clean["registration_date"].dt.month
)

patients_clean[
    ["registration_date", "registration_month"]
].head()

  registration_date  registration_month
0        2024-09-09                   9
1        2025-05-22                   5
2        2024-01-06                   1
3        2025-03-12                   3
4        2025-04-12                   4

In [360]:
#days
patients_clean["registration_day"] = (
    patients_clean["registration_date"].dt.day
)

patients_clean[
    ["registration_date", "registration_day"]
].head()

  registration_date  registration_day
0        2024-09-09                 9
1        2025-05-22                22
2        2024-01-06                 6
3        2025-03-12                12
4        2025-04-12                12

In [361]:
#dt.day_name()
patients_clean["registration_day_name"] = (
    patients_clean["registration_date"].dt.day_name()
)

patients_clean[
    ["registration_date", "registration_day_name"]
].head()

  registration_date registration_day_name
0        2024-09-09                Monday
1        2025-05-22              Thursday
2        2024-01-06              Saturday
3        2025-03-12             Wednesday
4        2025-04-12              Saturday

In [362]:
registration_day_counts = (
    patients_clean["registration_day_name"]
    .value_counts()
)

registration_day_counts

registration_day_name
Friday       1730
Tuesday      1725
Wednesday    1716
Saturday     1710
Sunday       1689
Thursday     1682
Monday       1660
Name: count, dtype: int64

In [363]:
patients_clean["registration_day_number"] = (
    patients_clean["registration_date"].dt.dayofweek
)

patients_clean[
    ["registration_date", "registration_day_number"]
].head()

  registration_date  registration_day_number
0        2024-09-09                        0
1        2025-05-22                        3
2        2024-01-06                        5
3        2025-03-12                        2
4        2025-04-12                        5

In [364]:
monthly_registrations = (
    patients_clean["registration_month"]
    .value_counts()
    .sort_index()
)

monthly_registrations

registration_month
1     1214
2     1031
3     1140
4     1179
5     1144
6     1103
7      851
8      846
9      807
10     917
11     827
12     853
Name: count, dtype: int64

In [365]:
#year+month 
monthly_yearly_registrations = (
    patients_clean
    .groupby(["registration_year", "registration_month"])
    .size()
)

monthly_yearly_registrations

registration_year  registration_month
2023               1                     286
                   2                     243
                   3                     244
                   4                     300
                   5                     284
                   6                     291
                   7                     273
                   8                     285
                   9                     260
                   10                    309
                   11                    274
                   12                    282
2024               1                     339
                   2                     267
                   3                     286
                   4                     291
                   5                     293
                   6                     282
                   7                     290
                   8                     300
                   9                     273
                   10                    300
                   11                    279
                   12                    291
2025               1                     288
                   2                     273
                   3                     294
                   4                     316
                   5                     287
                   6                     259
                   7                     288
                   8                     261
                   9                     274
                   10                    308
                   11                    274
                   12                    280
2026               1                     301
                   2                     248
                   3                     316
                   4                     272
                   5                     280
                   6                     271
dtype: int64

In [366]:
yearly_registrations = (
    patients_clean
    .groupby(patients_clean["registration_date"].dt.year)
    .size()
)

yearly_registrations

registration_date
2023    3331
2024    3491
2025    3402
2026    1688
dtype: int64

In [367]:
yearly_registration_summary = (
    patients_clean
    .groupby(patients_clean["registration_date"].dt.year)
    .agg(
        total_registrations=("patient_id", "count"),
        unique_patients=("patient_id", "nunique")
    )
)

yearly_registration_summary

                   total_registrations  unique_patients
registration_date
2023                              3331             3331
2024                              3491             3491
2025                              3402             3402
2026                              1688             1688

In [368]:
yearly_registration_summary_sorted = (
    patients_clean
    .groupby(patients_clean["registration_date"].dt.year)
    .agg(
        total_registrations=("patient_id", "count"),
        unique_patients=("patient_id", "nunique")
    )
    .sort_values("total_registrations", ascending=False)
)

yearly_registration_summary_sorted

                   total_registrations  unique_patients
registration_date
2024                              3491             3491
2025                              3402             3402
2023                              3331             3331
2026                              1688             1688

In [369]:
yearly_monthly_average = (
    patients_clean
    .groupby(patients_clean["registration_date"].dt.year)
    .size()  .div(
        patients_clean.groupby(
            patients_clean["registration_date"].dt.year
        )["registration_month"].nunique()
    )
    .round(2)
)

  
yearly_monthly_average

registration_date
2023    277.58
2024    290.92
2025    283.50
2026    281.33
dtype: float64

In [370]:
yearly_registration_summary_sorted.to_csv(
    "yearly_registration_summary.csv"
)

print("File saved successfully")

File saved successfully

In [371]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\pugaz\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\pugaz\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [372]:
yearly_registration_summary_sorted.to_excel(
    "yearly_registration_summary.xlsx"
)

print("Excel file saved successfully")

Excel file saved successfully

In [373]:
#Department level report 
final_department_report = (treatment_department.groupby("department_name")
    .agg(treatment_count = ("treatment_id","count"),avg_treatment_cost = ("treatment_cost","mean"),avg_treatment_duration = ("treatment_duration_minutes","mean"))
                          .round(2))
final_department_report

                  treatment_count  avg_treatment_cost  avg_treatment_duration
department_name
Cardiology                   1900             4000.77                   76.06
Dermatology                  1274             3840.09                   77.14
Emergency                    1818             3982.33                   77.87
General Medicine             1968             3984.60                   76.16
Gynecology                   1731             3954.92                   78.48
Neurology                    1558             3756.84                   75.90
Orthopedics                   758             3955.17                   75.28
Pediatrics                   1885             3890.31                   77.05

In [374]:
improved_percentage = (treatment_department.assign(is_improved = treatment_department["treatment_outcome"]=="Improved")
    .groupby("department_name")["is_improved"].mean().mul(100).round(2))
improved_percentage

department_name
Cardiology          70.21
Dermatology         68.60
Emergency           68.43
General Medicine    67.28
Gynecology          68.34
Neurology           65.85
Orthopedics         66.09
Pediatrics          68.06
Name: is_improved, dtype: float64

In [375]:
final_department_report["improved_percentage"] = improved_percentage
final_department_report

,treatment_count,avg_treatment_cost,avg_treatment_duration,improved_percentage
department_name,,,,
Cardiology,1900,4000.77,76.06,70.21
Dermatology,1274,3840.09,77.14,68.60
Emergency,1818,3982.33,77.87,68.43
General Medicine,1968,3984.60,76.16,67.28
Gynecology,1731,3954.92,78.48,68.34
Neurology,1558,3756.84,75.90,65.85
Orthopedics,758,3955.17,75.28,66.09
Pediatrics,1885,3890.31,77.05,68.06

In [376]:
# Important Insights 
# General Medicine has the highest treatment volume: 1,968.
# Cardiology has the highest average treatment cost: ₹4,000.77.
# Gynecology has the longest average treatment duration: 78.48 minutes.
# Cardiology has the highest improvement rate: 70.21%.
# Neurology has the lowest improvement rate: 65.85%.
# Orthopedics has the lowest treatment volume: 758.

In [377]:
final_department_report.to_csv("final_department_report.csv")
print("file_saved_successfully")

file_saved_successfully

In [378]:
appointments_clean["satisfaction_score"].isnull().sum()

np.int64(9929)